---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-nfs
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 200Gi
