---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app k8sgpt-operator-config
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: k8sgpt-operator
  interval: 1h
  path: ./kubernetes/apps/ai/k8sgpt-operator/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  retryInterval: 2m
  timeout: 5m
  wait: true
  dependsOn:
    - name: k8sgpt-operator
      namespace: ai
  healthChecks:
    - apiVersion: core.k8sgpt.ai/v1alpha1
      kind: K8sGPT
      name: k8sgpt-ollama
      namespace: ai
