---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mcp-context-forge-postgres
  namespace: ai
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: qnap-nfs
  superuserSecret:
    name: mcp-context-forge-postgres-superuser
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
