apiVersion: v1
kind: Secret
metadata:
    name: mcp-context-forge-postgres-superuser
    namespace: ai
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CsnUipSNfh0=,iv:sINElBz4kxXHUqAqN8Tf5gFAP0KaZtAX7iBkJs8bvxs=,tag:C0Px8E03rwKxiArc/qQPEA==,type:str]
    password: ENC[AES256_GCM,data:E1TJTK5+8QsjJX2aZq6xN3G5ynE=,iv:EyQNkvBmQWVIHYYj1+HqVOTfQ51MuJHk99NQHNwp0p4=,tag:DeFPWt9nbBW2lJVoLuWqTQ==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRlVmY3NwejVOMGRZRUZP
            WGNiOGJWdE5RNWdSTDZ6VUV4Um1wci9ESlY0Ci9KbGhIbUhTdmpTRmExNmlxaWJ0
            MFh0SmRWUnJld2R0VTRUL2JNUHkycUEKLS0tIGV6VTY4aFR4aG1QNEpDWmJCZU8y
            YmtiMjJrMDdHdFFkMlM5ekE4Yk9IRFEKu7bJ3IrvOMTEv91R5LrZPVNSgeOkfCsa
            hgzqKa6RXLxwxsuxQqY/bvjwM03YHRBiqQjcNpKbyaSlNGPlAtjt8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T14:52:16Z"
    mac: ENC[AES256_GCM,data:vu5dO3qnQ0Stpe1e+1FbAOMRyXsu/a/mFufBWR7GlXtQxUzyom8/sJRez2CGTJzNkp7Rq4CN8rmWEO05kD4Er7scNU0YTnllzxM1/W3goOEhqoot0i9MM5x9jP52efLzwJSbqSKDa7+AvS+7f6MCocwpzOT+nAmCVxVEZrWjQvQ=,iv:89VeohsDCo6nBsEOHMCESEWPeERiB4g62C3hViViu5w=,tag:jI9Y+o5x0C85WcQ74XiwrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
