apiVersion: v1
kind: Secret
metadata:
    name: mcp-context-forge-secrets
    namespace: ai
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:MojPEsZM+XhjiRiYQMcbfWMJ6BqM8eMxwgQxiPPETc4vxeg=,iv:Qzi3XAgBCzGcv6eTNi3C1muBopf7g/EhWmSEwGqPDrI=,tag:N1Z2fpPQUgydBru6a3NscQ==,type:str]
    PLATFORM_ADMIN_EMAIL: ENC[AES256_GCM,data:iW2cBHe4/D3BBol1o1TNrxZvdz+QZg==,iv:vgHZXAWf9GT9P6/uIiybtVYVlSYnliRDqbFJL1SKAd4=,tag:vVRoudE9jAAG6ikzf67k+A==,type:str]
    PLATFORM_ADMIN_PASSWORD: ENC[AES256_GCM,data:p0nkvcaPCQkWk1Autu6zM2OQc370Jqc=,iv:fsu2J1JSxFoX4CFtVzNbmiIUOggDq3tH6lP1ZUlFClE=,tag:95K7MyS3Uf41+aPw2NXYOg==,type:str]
    PLATFORM_ADMIN_FULL_NAME: ENC[AES256_GCM,data:9rlJho11kqwbOw7myZa+7h3IYrji/Q==,iv:Gf0gr1K6DFMMIm5FASr73IrMR1tYM+ca4ks8V4FBleI=,tag:63WdzCYTMKbcLZlbLpBLuw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:KmbiNAcCGNi/lQBLE5lkpY/IFEM4gM7b7NF7a6hjsvKgTt9MEdlhieKwh9264c7645dq8xNkOc644bPzraBwu4FLbCOe4iEXSy7lPiTKtpSBr+QHzmChUQznqAdIdyw24C9uz6xNY/tYjMemNY+irpm+WuOC7aPtTNUzlaOwmE1+m44=,iv:W+NPzMCU7ZJVzm9i7e4QwoTR0pZtdOSqAhZrGgiWkIs=,tag:j7SiRBb9+uAUKqWG1XOG8g==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb05lN3BUZnpvSjVOOTJn
            TlZrNW9paUNoQVdCek5JQzJLNFZVM2swZ1JnCnVISkx4ejNVZTNvRmd3djVIcUMx
            ZTMvWUZ6RHdCZG1XYUJqQmFXa29xOGMKLS0tIDJaUjE0OE9Zdi84bUFHbnZIdDNh
            Qmx5MlN2VkpiYm5WaG1BSkRDSDY3YkUKdWVtNmVW4vomzXGUy8bclgGgM8q7fXRw
            W2Ad68S+zzlowRGNVr1xi8m66EGhT/ZsISE9t5MpdaX6EdBVEDERIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:47:06Z"
    mac: ENC[AES256_GCM,data:QwRBE8TaxGC2FbaN5YajknFb1XmVUEbxj1QvSgyBgmuJs5lloURb1+v33aqqLgpHhcnYuCpRUfND7yZqElHP1oawwP5YeQ6TmXs3MXTQuDZJQnlGfljBGyjdytsJYBoYURoWoh/TwXin2fgCTSeLz6VvL0x8DJwP6VfKOUH61D4=,iv:IGVxytwfiM/vPZjUDfVGPcL1tqta0oVlM26WMyt290Y=,tag:Bos33jbvKpTqCjaR1ce3dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
