---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntarr-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs-db-sync
  resources:
    requests:
      storage: 5Gi
