apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-metrics-token
  namespace: observability
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:fFz1tQ/MRKkkoGs8O1jbWLXDpUFpfSjuNST/fpltnHQYwa3vdNWdYNwjtdU96QMHNiVfiH6gRqElpp73RyYbqJuD+3oE3KKd6wSZwM1hPhTrYmycNfY2898nscYq+HZuNl8a965QNidJynQ7Kie0XuvR17CWyVuzjBCJnmypA/E98QidxL3bGW1csHOGXg2yHvYns3NwmnSjnT3pOZ4H1cdHCOc5EYc9SSoB0UhufxZjPF6my781,iv:DzU8XxlLH2tpI/hCPbRjMX9xrgQ2OCu1ftoyZuOum/M=,tag:c2sJUyK9PrzNBGufVpcxfA==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOUZwYUlUcTRPRkVNS1FY
        bXlsS1lhWEsxQUVrL1hNaHFvekxmUkdkYURVCnIzaVFyc0dQT3pYNXdaTnNHYWhL
        dGlUbnBFUmNrakhKZW5Hd2ZKK0F5OTQKLS0tIEY2QlczcEpBdG5rbGtiajZFM0pB
        M0kycjA1dzBBcWxPdTlKM0RMelVid28Ku9OzqzgY41c2975TAohZ9OkKRQTNYre7
        aT2CKjWQwpBusi+0vuUFxbiB2p/o6N5Yx1Jwa1WHZoigS/7Qk8+BIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T22:18:17Z"
  mac: ENC[AES256_GCM,data:k6shye/UGRGtD5981DIsFLPVsslf/HCAZLj6vKlQBTM/J5PSpEUPmPkLHRMzwSr+lmOFyecDcUGOgqm+1W4k2LEB1m3Y+X8u60t1nelHa4Mb/kWwZbekjfs+9iEOnOHayfulUNj+ZOaWZ4EvToVY/Sou1QaA00K+NzF6MSD7nM0=,iv:TF0U9PC8kbxcYYdbLoNKo8x24DKO8YOpPrG4nlBWcBI=,tag:qKEr7oOD8wqiDX13XvRtYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
