---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./shared
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./booklore/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellystat/ks.yaml
  - ./lidarr/ks.yaml
  - ./listenarr/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./slskd/ks.yaml
  - ./sonarr/ks.yaml
  - ./soulsync/ks.yaml
