---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: kubewall
  namespace: observability
spec:
  targetRefs:
    - kind: Service
      name: kubewall
      group: ""
  validation:
    wellKnownCACertificates: "System"
    hostname: kubewall
