---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./ocirepository.yaml

patches:
  - target:
      kind: Service
      name: kubewall
    patch: |-
      - op: add
        path: /spec/ports/0/appProtocol
        value: "https"

