apiVersion: v1
kind: Secret
metadata:
  name: jellystat-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:9WKzURjPvKTut1JGNhlc3UVIY662AXogWdJbF2VQBr5ZPihJXYDoe84wj/JXNo0W1wMWmeXWNtKZ7ODpks1+cAX3,iv:SNO1vS77gwEaIFj6ognT6PyWZ5Y8wqxjCZVPAdqhp4g=,tag:U8iL9GK9dFG2lVTbuIoDDg==,type:comment]
  JF_HOST: ENC[AES256_GCM,data:8Z3mG8UvvPX0c5aZQ2jLMJANn2PCQEWoJxRsxtb2D/SC,iv:DHLewbQQkOaAxd1W0QXPi6l1osE4AUaECiJak1GXwWA=,tag:5b1VInL+84/Rbm4sJosH1w==,type:str]
  #ENC[AES256_GCM,data:RJvWXyVFJDbYtHtfZW9mLXFRQLsWLUvIE6VuB8lQMF8sRDldnidNr9BsLIdcWUWO6YdD2BKXWq8fOZctBUzDrVkgT3XFFcDNZRI=,iv:FMWyIBKieu+PHef9I9mBHVIk6dIVZjoYIb77WkD+itM=,tag:KnXgXDWnBhzDR4k3PAu56Q==,type:comment]
  JF_API_KEY: ENC[AES256_GCM,data:FQxl8m5ogyDTKrz3qptrq4s26dJ+qSuKW9EmhO5RYg4=,iv:KdFx28GtIwW95+aaIy+s/AT54j2dFd/VeYEyvDATnSI=,tag:IyBumIfsEpSjfXMSAFZVvg==,type:str]
  #ENC[AES256_GCM,data:JWllZc2zBSXV2Vll/6PotpBKL+yNFoBdR4hNAkSCJmfVNZV4Bw6InG1+suO4ax1uqoJv0bNlIA==,iv:p1pXWYCnVNeRwj4s1CACD/OqGhz8UqZYTiDjZa2pY1I=,tag:8wFkTkc3srNotQIJw8thNw==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:p9KmKadMive3vpOHqPwPUcPe9OpS5NbPj0/qDecIL71oJzmsipIom1NcW2I=,iv:87uS062T6YDPF532I+TMbaQvCnw2JCxNNQWvHLakNPg=,tag:k1hJ4DEGUQ7rwhwixAE8OA==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqREdDc2NUeUJQblJrNmN1
        K2kxMWlPclNOWGFzK04rSjNOamFrNGRWKzEwClBjU1Z5cjBTR0FYS1NlZWdFT1J1
        QXhiakw1VVBuQkhXQ2FsYWRzbFdPancKLS0tIElpbGtPdXhDNkFxemVTVUJUNHd0
        UnE3Qkd0b3ZrUVIrSlhwZDR0TDl5ZVkKvhHBy/GCdIADwywQ+pmRJk0PVlB/zqJS
        HrTwPT2/eEmlH+90575lyTKmVdKneviAbOlzxRLTKgvUgRsPhusxwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T18:41:41Z"
  mac: ENC[AES256_GCM,data:+VFNaPDHq4bexBSvUlc7bCJR9b8pLEiZLwJMmCbnYXGpwinUtL2ro7MRqpokgxv046qkUe1soVxeD9pWF+B6s2SThsPc2HZJW20T+YZG7FtNTErS5CnaeNeQgPnhnR3XEhYg38lcM30If92izQQoUFSe9Dwnoo+Q+YVApDGbFoo=,iv:g71DKFBN2jWD7wHuSRhls1+FNoAgBlE83p94bvL6078=,tag:4xnvRX4k9xxrmyIUMv1u1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
