apiVersion: v1
kind: Secret
metadata:
  name: jellystat-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:AQcafOTgcLPCUgPeVUw6MAcCyYrSznTChnMmwZ9snaCzERmUXLHZAc7nowwcEEDu8gB5VSHlEyGgXA2FBNSlZsGE,iv:JoeXzbA5EBp7I6PN/3MffKYjGUUWGCtBprFAst7q/ik=,tag:heXlzU2UvvckrZQAXfp5aQ==,type:comment]
  JF_HOST: ENC[AES256_GCM,data:cP5ZUUdzNSq9JTxN0VGAjRMqM36vGc2DHdTcOXSBOju8,iv:4Z47l4PLDeyxVeSM1sITitJa/y6hQ4xHvTzuM1K8PY8=,tag:NGUjp/qz619u0hLuE49fRg==,type:str]
  #ENC[AES256_GCM,data:ztDRTNDFnMw/+u7hV3NZFLDi7w+vnJI41NxdZ2FfJD6ag1KRN83nUjGNShXiimGuXMY/Op4z7rgFnS3SdU9kHO0VVvDCXPLhlOg=,iv:szaz02EOQ5KPNEayAbiRgKt0fFQ/mTp7T/vXry8+EfI=,tag:s3nPqpxaQI2dnjwZAIUjIQ==,type:comment]
  #ENC[AES256_GCM,data:PCJbmLuQI8vXmQENyYt0x2CDndSAqVfh8TKUxivKa8FzPXx3+DhCT+ya0c2XyJms/J8=,iv:UCbxvsi1N/iGpZkHHU+8UVLb3pFsJ66EJT41RelmKdA=,tag:jB/X1bOFxJNctDMKt4AhRw==,type:comment]
  JF_API_KEY: ENC[AES256_GCM,data:CHaP0uhBj3wk4RmnrHsws33Eqec4kMnCvg9jhS/xSec=,iv:9GoceIVpHgvboc1mzkmF55suTWLppaDy5ZlzA3qOCFk=,tag:6vRThU9I5qJhOKWbZhxeIQ==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3THhIZ0k3ZW0rWmt0NHJh
        d0NhUmpqejJMN3p2MEljUjdFZXBLNm5Rb0NNCmtnWldUMzU5MTY5WmNNL3lUVDFH
        ZWhIS1ZJam0xTW1Dei8wVVA2RTNSY0kKLS0tIExHYmRZL0Fhek5YYWNzSU9BR0VY
        RVNLRnBlMmRSUW5EK2pJL2M0NEtMTDAKxDoAmvNouAlCCmxPt0CAmQAFTv/Bzv26
        /a9S6hAMFErDmOB1j4pmIPNFh5npaIiD8M2aVoewyaYBWmTAQBXNbw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T18:17:34Z"
  mac: ENC[AES256_GCM,data:8SDXmSHbv+6Uk0swxIgThNaw/pbOggO/ZmQJlivKC74zIJKX+gk6+duIqkHmRAImFQ5yxwj4ZiF8Q5PfJ4GwqLhiU4MKSVahtmooYS5UkfSiKBcDq41J0zHYB1mHomyrA3XL6Hu3+zVvrtubXgBNkepm0BPQxzqlWAy+W6uCiVo=,iv:tNzamdDmxMFPe4lVM+edRVJm8tYI1psPROilA5U3Bm4=,tag:Wwoci/LRh+AqJuruweEkZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
