# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:d7J1755tGjljJiSJUyAa9f+vR90PTi5hhSyzBvwMs1RevLXLYhGD3g==,iv:8BBG83JWH+FEqBSXw5S/Vu+L1bFtnHoPjTQzavwQHR0=,tag:mIZLgha60JfLccnpaf3uHg==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRjlzeFdndkJoSjE0OUY2
        R2UraXdaV2w3dzl4Q1BoZWdNY1JORjFBSlRRCjU0bE1KYTNEWE1IWkxyN251ck04
        MzFOaFNRQStDNHAzS01QU0hWY3d1Y3MKLS0tIDR1SXRNTmZkeDJmQzlWaXpwZ0N2
        UWZzMi9JcFR3dG5NUHhTMHpRczdkOFUKbGQZQHkyKaIiGbReSOV8ptOFOG+Xp+UU
        ObNvZQS758LPDFTu1XjDhJNnDfb3om/ZzkSRAbj5NV2jOEXsdqS0HQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T02:55:45Z"
  mac: ENC[AES256_GCM,data:2ykhSc7SKIlRTamWenJXpLZHgWaO0Kxs8ZYQWnK39RW+nnNJZb2xXaNK6ZDsIbXa6Tshrd9fODZhaFHchG/j91g2Lvlgr9uBulCtueqjLwodsgmZDlEzuUBXAwmL3408dP14O9cvWKNNvu18TCc7OI5NsplJgrvfzHKzSU9wlxI=,iv:JfExkFOt9/Ecm5lv850d99QEHIbELZaNczOx4zxYYa8=,tag:8tGi5i6XV4yUQuD0hePUWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
