apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-secrets
  namespace: ai
type: Opaque
stringData:
  #ENC[AES256_GCM,data:Ar+1IqqbajpWTG5Iu6ZaxJIYSAi50PYyHrLX8x6Sv6zTBVhKY/u9OvnN2dF0MQsC3s345Voa5dLXshw=,iv:rOkR5Ba4CMXY89Ue3R7zxylrvyPUseTj9Q9AiEBTunE=,tag:UonYREfix53hv3vjnpZCgg==,type:comment]
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:2eCgT2CGSAgj3rrmeHSLy2PF0BvX1rxI95NTcYb2PXKfqXezI+SjzGn1AXM=,iv:BE66EdbzZHqQ1rfY1OCT+qkttPsIxnT/e8wOUi4u5Ww=,tag:VPzLZcwvDE9waXxd+Ps63g==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RlZ5UEdLNDRQNS9ncUEr
        NXVNSTh4TkNEMHBhZUN3SFp2a2hyZ2hjY2pRCndtcFdNaW0yMnZWc1VCZ0t2azJZ
        ckxwbjlKZ0FNL3ZaZlI4eWdHTUh3QU0KLS0tIEhabTYrQ0F3YkZpNHZvUkRqTzJ4
        Wjk1VmpBZlNRS2NWT1RSMFV5bS95SGMKDjcwukFsPX0UCujb3NqTzsM8AUcDc90P
        vcBQl5sbEgnJQq2+em1ytJuKpFwoEDjEgGvZcMOFedXnewLszkEoOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T03:16:25Z"
  mac: ENC[AES256_GCM,data:JajsKXQ295zPZ01v0V/68EhI5h5OhM1fjrV/Zk8XgMe4RnR5dt1woKCV6poUVxtGDFgIbhrBSzUbWKcWptV0N8P7y93WwTD9aAG64r7tKso1WccJXmCucYJqNhnB9iZRT8jSAtDDMWf+CsAW/Y5DO4gtLv3ciN/8T3GtaTQQqZU=,iv:ayjM11NEsJWs8fS3DIvghZibr4h+0HUIUs1w9azCfRE=,tag:nQByqRC0PPl9hyRBKDhFPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
