---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./thanos-query.yaml
  - ./thanos-store.yaml
  - ./thanos-compactor.yaml
