# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: observability
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:uqRp5xAJsdxQ/e7c2qgjK3zGGJ6Q/PB7IPtCkOypIdIiCKbS+QyJXbGmDhLVS5xym7DMh7X0b1wK1PdFKhajfPAeBD7aqY9Bex84TOGmFWnZD+N+RWOxQWtjO4QMw0An/QvDzuZdxc17TMYaiRhxEjKPdQvjV9gfWM2Ui0y+wI8c8/7KRy2yUwo0+wdAmH3gdvz4ICq6mt3xC0uoI68jH0hXavPhqaxLUOlXo1isHsO31z4HNX6Zf8g18fvWwQf3tLKorIZnuk7tbqwcTYzRWJCrtPKfMVjdX2fc+JqtUPmsyqZIWj4B,iv:R3b7uhAy2N225ERRIO4SeqvPqzR9w9vc2BN46o7xYI0=,tag:auYmrv1U+/NBwQn8rTGpRA==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwemVKSVJOY2x4VC9aaEk4
        dGVXNTg2L1FVTzlSRkhxMUxWUGRuc1l6T3dJCkRyT3FDT1VnTnAxN2lTRk9sWTlI
        WGJnSlpiUGpiWCtnSEhELzFLUTdNUkkKLS0tIEFHZk5ITXIwKzZEUEZic05iRmt1
        dFZmRWhMMFB6clFaSXYzM2tUR1RzVDQKuTGM+E3WLk0wJasIt22GCmUcxtPOV017
        s5YAcOZj1ieGPxcK9qSzbZlnkh4mh+uIHVqTJCI+o4cj70D8uwO0Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T02:53:07Z"
  mac: ENC[AES256_GCM,data:e/9/zIJS5RUkD2KT3YM/7aKBnNwhM5IvGcW3EqBYWYoF0pMKVH4saj6LC2ogFvWT4UUsjBsfiTTpyMOZRXVXh0Zo/RHM73hcJ0BdevLzJLflwC7fKC9m4DmBRWBseG1ouhViD2yKUFZoYhI8U5sdMeelZUGedbPs2kxBHo1dLzg=,iv:t6ug0itfvlXOG/2pZ6wlPwgrXASHtoZwJrtshNFeDag=,tag:qZUkOL7Emx4AnPAjIaFJBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
