# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: observability
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:UHPAXU2EwQYHreaSspOwT3uMmhlCLT5KDxRGkiq6L9x2i4XOIxpRCnGVSQNcp7CjcD6074U7oFNvsDtC5GwFJBrHmzg2ofm8UDbTUnK22X+HE3ZQvXGSkNhaa1IYADkIVB7Yei12wbWLLByQMI+L6QgvQuIEKv8MQT6mCEaleLdSuLUdYWLUNlF+A8dy/dyKlcNRf7tzcFO8kd+vDSF9CTTyaWUorlTa991tb7GNyfzqIepiHCOQNYtVS0NNMR0liNSXkFfAOyuywVhF8OPXhD02bikRGoVZM2o/qMTOag8MUvyiXJNE,iv:rOVHA0atu7V1SD7Yalw8S3otwuBiCwysC5gN4gHa5+o=,tag:FEwE/2Ew22ha/C+XaqD3bw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZTNzZUFoaXJ3VGJqMWtB
        WEFwQzlIckEzYThHbC9jR2oybjFwbW9Rd25vCnh4a3BkS290TEJkcGJYSjFya0s3
        cXBwaWhSdzVZM1NtT3pLVjBSSzliMHcKLS0tIFJOamt1QlR3Y0oxZm44UityTDFF
        RDA1M3JNeVl3WS9yUmMvQUNjSlpjbzgKk/FUfFsqpPVbx5g0EeduKinIrd1Y2w1K
        XrlRUbRVEB3QPPOLCvPoPLT+xifz5Lo9AlogBTaWmt/jjywgkeWHuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T03:10:13Z"
  mac: ENC[AES256_GCM,data:r8QmrBB6SQGytQNK4FndTttV8xFKv4luAX5OJldrEQoWCrEQmGDHckbaW8PL8gctfZSklUM282MsUsBm8wuj6njikJsvwxljZkTSvzu/1NA4YcgfPY3jkCuOL5W6pcd0Q1MjkGs6LR52SGK7ytvhgL+JAjHq7KhowKWnLkMvKF4=,iv:79qJmri28XqiPlDgOLM113heVq0d6As9K7Q7IOUNzqc=,tag:7BDNVVXFVuaMZ9PkOKJyEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
