# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-secret
  namespace: observability
type: Opaque
stringData:
  objstore.yml: ENC[AES256_GCM,data:2xSIvk1jI0cD2+4Yz9Jq2LT3rm81oCDjzc73gGRhEac26lZE0tZClI/meRtJ55G0ki2FpP6ozqR5Jo+gZWMpdQJyz44ff3G69pMdgHFMkVWujpCWxxnGNe1cZX8f9Y2kvUhTjNkSmNhAchxgu5zm99FbWYrFHTjq13EnA2hyJCnfC5X1IDI/BrHt9DS1boTIdKbr32IRUclA4KBaANb5uS/G/lGPr5dacTriJRr/gGJWkLRFE5vsbLeN6Tkfqwwa92alXmu7+0FKo/YvchRubf8T6pnnqBZh4yVnhLHq7yj7TuIF5+PyiTxAiR5cO94=,iv:AHXL7mr8koJ67hglA2LL/mOBjDSyPy+QmXvxCAkIjkE=,tag:IrCGww6uoFRUD9TAqYdb+g==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK0tNbWtLMkwrOHQ4anhv
        U3VkZForZi9uaDNMcEVXWWFLbWx3VkNYVUVFCnFKTSt3YmlwQUVuelBGZE42RDNk
        SDdBMXl1QnBTZCtmNENqNnBGSm1nN3MKLS0tIExWWXJSY2o2NCtpSEc0anFOVUMr
        Mzg4aGZzSXNuSFlJOGFMN05OendEUGMKwbrNlTEthVIrr9wNC3x1xxsrstHYAYCS
        q2CjKyWv0OaesiqSRwk+NOAyfQTkTLayiI/SwD4G9ePSE4B+niSycQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T03:09:04Z"
  mac: ENC[AES256_GCM,data:0I2e7VFVOOmqE5Vmfx8rFu/mQ4Lvktvu/39ri6RtT+Wbv2yt2aapLAWqL5jsxzJ0xbx8/bOaKA5IvNPXuiy3VlryXMZpcoGboX2kT5omloqXkcu985Kz959Dq2QGJ/homNTxzq+lP/NgkXJVGr6zZI5WrpCaUqkn/PRHC+htpo4=,iv:Et7RRotmwGD1nKOcDYiaiatxa1f7b4X7MNdLbLiZA5E=,tag:EmafZlQEHjoYD7DnnPVbEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
