---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc-config-nfs.yaml
  - ./pvc-media.yaml
  - ./pv-media.yaml
  - ./cronjob-backup.yaml
  - ./secret-api-key.sops.yaml