---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfs-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs-db-sync
  resources:
    requests:
      storage: 10Gi
