apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-api-key
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:sptsjw792kR8cuA+hDaiL1SFu/NQA4KevK8t9f6uZMVQ19XUgYjTywpR3e5cjhKaJtMrr/fcnkS+zI8PUgBn,iv:7K7joXmv/g1o3vnTE2dW5HR/8BVR40XaCEG63nRCRIo=,tag:SVhGmglC5mKJA1Xfd8RWAg==,type:comment]
  #ENC[AES256_GCM,data:3dshsnNld75yfdqt6zA54iJGttweY4aw4oMPsdJPwhGqkT1zDmZyEYwDSExthXRNahTERocIH7R+tGz4tCfFuXxFUk0eZiX9cqjETSe8TxBlOl/KVwyeD5ke3LDQHTbKXfz2,iv:/pDzIqKUAMuILuIW2AvoNQGWUjhtPRik4kmeZ5/u3xI=,tag:nINK4rXn+xBLQAg63+ozKg==,type:comment]
  api-key: ENC[AES256_GCM,data:kmU8HP0Vx/u2iVv465PoQ0MvpxgihwwzTyEK5h9IYGo=,iv:Lr8sk21PM0RFPRsk+U5g1eex+T3h6LFddN8D7hOZXpg=,tag:wQ0m3xoWkGMQb5uqj/7Shg==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS01MZEI2ZFhWWllCOW9R
        ZVJUOUh2QWJUNTdER1gyMm1SRWQ0MDJidm1ZCjhialpuSTBFcm9HWHVTQUV1V1Bw
        Zk83QVBCNkJ5b0t3V05uMWQ0OXhHZEUKLS0tIGZxT0tkZUFqU2lyT0tpWTZpUVlI
        dkhMUkJRRXdES2ZVVFV1Y0k0bUFGOWMKU9pH9/ZRsGd0vepH4PtCRbG4Kkq++A0b
        n4s4c+F14dbZwpn4q8Mxw7X1wm2sv+r1OyTKj7Wa98NCgM2we/afrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T22:53:46Z"
  mac: ENC[AES256_GCM,data:wzU7bYh+slUxfuflsobO6KR6ctJpebOl7HVP+4S4K+pRTg9V7mCDfBTo3+2Gh2UG8QrRYgECIpqX22LoVaA3DP9y3kuAZ7PWOuDatQaTj/p2+rZkE27r3v8xvv9UX/pRMmH7YlXJz0a2fz9hPSex7HUr8YFEP5+7kMAGTcfkNMA=,iv:wMagMDROMVBtCjs+YZPWVzvDGCtNvH5FdNvy3Z/pO5E=,tag:/NV3gKCoLTibhv+F0kc8qQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
