# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iCpERBh484uCSJ3d59SsSNp0VR9jiV1X4TSkwN5e8o4=,iv:f6VKuLHj/LzgPKEFkxJEoIItECUy3Acr7uK5c9IVwJo=,tag:c0cj3cIXVJqKnmbn8fF17Q==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZDRVRTlXSUJRNDVNRS9t
        dlBXNlhtZ2xpR013K1NTWVVRb1FpamlrOEFFCkpHQkVTYXBCZVBOKzB2SFBzNEZP
        dUJlUG1Wb0FLVTVzQWZZS2w0dGZyODgKLS0tIFdUZkx4cFpJN0MrcitqVmZ5OE9D
        VnYxQWtXTkhjVUtsZ2VDNTRVVGtVUlkKNz3FRNiWeUbSvUQsxisJF5mD7ZxSR/cl
        Z7+sdxGOjvNDmYY60LaaVwIJDMjxEo8ExtaGdkO8oIic/1oZTp2vzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T02:55:45Z"
  mac: ENC[AES256_GCM,data:MAhBIQWCyZJ/My6oPrUh5YW8NAJztemGMnieE2pOOfFjtz8p9wlRfckjUqH9oE+xkkbI5AKGIm77F8/BkEHUHEX9v9xv7xf6uT9Cp7BevzO1QGxXxi/u5lJNQORXJ5gy6xforI4exGVfjnjeoETLCaMbHo37Sv51IZO6/3kpdKk=,iv:uHX44jWfqOA2qasg2FFphItmcHxB1uO9zMkjvnjPIgU=,tag:ED3U9PBMq8byfEUrqPeLXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
