# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+wduOOHvM6WihLpgyIUkhElvUHg+lbe9qP1DV4vPtiU=,iv:ouaY1LXjK5eP25YUf0qTUlXDXJEW3W3HZSTpQHz3+CI=,tag:tGKYHAGsqTTSnsYXPeUzZw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZVduSzFlTXUrTlE4Q21u
        MGwxbjZ5QldQKy9tOXZDTFpVLy83NEluUWhVCjBML29SUUkzSGtIWVlScVRBOG5m
        Q3VVWkYrOVhhTWJQRy8zWUpyY0c2SEUKLS0tIHg4YW1aLytTVWJDRVNTQ2Q3aUVl
        V0RuRVZ4MGdoWDMyTkpSQmM5M3YvVW8KEnY2QN1QVApySCm6qiMZGj8nPWU6+iR2
        jIJsDe22Ab/BDeC3zBsaLZBnzPtlcAlME0kolnKNMoXI8KwmMuXEJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T02:21:53Z"
  mac: ENC[AES256_GCM,data:HzRSiCxSSXeJVUgRR0Ak+klkrU3LQcmlvPGeaNmtxzKxPj+81UwA/Vowf4opQKcYZoHaXHgAYd1XPGgnZ6Is45L/Az2UcXOTEArO2Qeux3ohHd4jorToUX0zDSi8aqiVHo8fkaEa2c+RENZBLsVuNPdrq+sDWvzupHQerN1w0AY=,iv:ZZOL30cwAFChn8rQo6n2KaXRMYjf7JocYnCI+vRyamw=,tag:tBFzNh37/ocT5MDToDfNxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
