apiVersion: v1
kind: Secret
metadata:
  name: mealie-oidc-secret
  namespace: home
type: Opaque
stringData:
  #ENC[AES256_GCM,data:brOG86x70SRWJggYg0PHkS+Si/ZCdWQJ09q3IJqcf1fbvoJ5,iv:FBxYshZUHB0QTOaa4+WPV+0nQB8rHuV0F+KqNNMni/A=,tag:q3Gp+apcKc09/sSslsokVg==,type:comment]
  OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:396xOQ==,iv:4t0NTznyXIM5xA3qRRPYM/1rEAmUGe+ZQHIgzq6Ttt0=,tag:QXIO2ul3v39EPJgSOTOGIA==,type:str]
  OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:MqZ7sg==,iv:hPxhd2leDUE3UqWhDeCWj7n6bg04wmwS8BRznccRKIo=,tag:7pnD5IFgHYIdSRSozgBCOQ==,type:str]
  OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:0eUoRsbVMEMEXrvo0NzGlFKxK55Y/VpXU/cpYcdmJiuEs+vj4vHIfKVc4v7tT2QX8SbkPxcXzalZ44aDLS19bXLGBjbmDNVuFU8nqXZPk/g5vbmiKWI=,iv:qtS146Kmq8rHbKYmCD6869boJ1smPuy8S/Hb6Yf2wVg=,tag:wG51V5aBDBta7Jrlpw8IXA==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:Fh/GNaC+A/zpvWiplBeyYgc+TRMGjqpCj5XsVIwdOe+RBN/bwJcemA==,iv:ZWLG8f08oRgSOkrjlRYm5iOZgXm/qSYw4SH9eORRP+4=,tag:xaU51jhjKDgTStTOafSl7w==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:HXC/G/lHLgMwXxJEEBEsnx2msAcJombaVF3W67jtU1lvM+WdtRU+eonrZm/LZdkl436KZi388RC+NfBUqm1yzyjEvPYa0hU74q9NQw6/3b6Jz7gjpflpM676DtVbQeA3JlR5GYYduuTq8aoX80eiB/7r6SEwoIdP24j552zAPDg=,iv:W/R7k1xiBMG8peyJX4ApJgo5mLmKj3/feJNXHxIohC4=,tag:3ZYtubwgUeqTCvw3Q8fxHA==,type:str]
  OIDC_AUTO_REDIRECT: ENC[AES256_GCM,data:RqeEFig=,iv:hf1lSBYX0Oy+e2c7VUr7KTKGTkEbyJ0kzO8mIz0bmLs=,tag:WMKs6oNDiLMDxMJ1ezipjw==,type:str]
  OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:tEI2kzzKTPhu,iv:mRFNfXUhqeBxFnstiWYSmmiNJ9qp2uM+3zeLV0NQdDc=,tag:G/UXcesUQcW3yMPdnrIcGw==,type:str]
  OIDC_REMEMBER_ME: ENC[AES256_GCM,data:fHHWXXQ=,iv:/Wu78PiUw+qEJjDUGyCJ//j/DEb0D9Rlq9hPnSu3KJo=,tag:WeAo1a6spjir3F+Xxmc6DA==,type:str]
  OIDC_SIGNING_ALGORITHM: ENC[AES256_GCM,data:wOdu3zo=,iv:qIfPbPfCCcGmxvwNJxbFN5SINEF6Hfcr7vT1AMU3/ew=,tag:xwFQvGqJkOeBWLIJR9Lb3g==,type:str]
  OIDC_USER_CLAIM: ENC[AES256_GCM,data:/5YVE/M=,iv:6DatCvUWkJ0RCfNku1lnrsm40QKzMUfbkkgEezw6I1A=,tag:oawr5R8EYbJp6Khf3CTzqA==,type:str]
  OIDC_NAME_CLAIM: ENC[AES256_GCM,data:0itAiA==,iv:3jB1jPju9AZ3ahmHdX5UgleFo5H9Bh0DkkU2/l/coB0=,tag:9czl0ElXQgDmAf/1owWqWg==,type:str]
  OIDC_GROUPS_CLAIM: ENC[AES256_GCM,data:kYCRYBFF,iv:b4Bb4RX9Qk9AfztjSCQz0iQ1cBL2Mpw/ult9HTPYJiM=,tag:zR4x7YJzWd/ADDOUHXHw5Q==,type:str]
  #ENC[AES256_GCM,data:1rCNk+qlRwI/xgnIaarY7KWPUA6n0zFK0D+Y44aXVCyI/TKqrNYNjKe39nuQYwoUJSwHsBpcMJt24aBC+wO3OYov+T3pw+iD6N9kvTOtFPoN71HW,iv:k3JjDaF9aJfe55LUOP6eaKoAK0QOjGBcIW3rOfD5e1A=,tag:YTdXGWaBmxu01vFKZ0iZAw==,type:comment]
  #ENC[AES256_GCM,data:nYusC+6fATp2zs6cfyOCufK7OlfKQ/DRFxRGCEG1AW0=,iv:nuueth4mWh+X5oILroKvoLmYeMU7qfTby6IGOlEWoaU=,tag:aGJFlcHHlFs0M/6E5nCx/w==,type:comment]
  #ENC[AES256_GCM,data:QQQ/iD/Ao73TdQPQMW1E199xaohFzDXtBYn3gPSeyvv0eA==,iv:uFxedm3oOtl45pXJHNXlZXVO6O0mLrqckLhE2J7LoDs=,tag:Y3sibz072I2q1q7DsoHHLw==,type:comment]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:84ybnjghvVhLk1W617VwlkKVCJLWb98suWFD7OOYGxU8Q/5CwTVjvSbfsA==,iv:QBZn9l1g5RhrrsgP3HGwv8lnLd9/8/WoZwYwUojsiAQ=,tag:Vvd2TxeHXqO+ti4EFFIA7w==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:4amIDRR+,iv:19oEQqcfRFAAhogi2RJEpSfJx8FOlmWWRpxUtSUmIAU=,tag:wLZnlaS5TCvGDHrnMsp3TQ==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:rqbj7luMBvk=,iv:uY5Yl5f/vEpvUKatRRIOmuxVGsnNav9b/cp4+kVCypg=,tag:MGgTCir4/jVhjeMMVcCPkQ==,type:str]
  OPENAI_ENABLE_IMAGE_SERVICES: ENC[AES256_GCM,data:kzru7Q==,iv:HGQ5bPdxRvrCQ2Z/8ciCkwyE/zTvYDWfuE8nrwbD7fE=,tag:m/r/tQhBhtQqIoeWtB/9UQ==,type:str]
  OPENAI_WORKERS: ENC[AES256_GCM,data:4g==,iv:JBUqmkmQVEk1P1WlAIegvYcxRQSDEss2th2RWnMaKd8=,tag:h5t4qwqswTIWPo+ZIqo+Nw==,type:str]
  OPENAI_SEND_DATABASE_DATA: ENC[AES256_GCM,data:he0wzQ==,iv:OZ7eLypD1Yps+mF9z+sUyrNP6hlGetPMJkhoWbD9UEE=,tag:yc/yYGmnFVWJ845YQItyDQ==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RlFvWWFmMWRNNW5iVHhB
        TGFVSXhDRm5vS0RDM01HS25UL2oyUExtVEFNClg0VnorNTdIbGdFOEV0enFBU1Rj
        ZjNNdDZVVkIrQlcwRU14dHBGampVYm8KLS0tIEdXR2VvMFRFT2hnMEJLSHgrZU42
        UFRLYzZId0M3ZGZ0dWZXazFZdUtKNmMKrfUOcW7Ha6UVhG7OaMkQhrvT54PMCihS
        g3Wh4JhyVr5eaAI35HzWNwu+1fXt4gOM90p+YuoWSRj732Ju2vLJEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T14:58:08Z"
  mac: ENC[AES256_GCM,data:bizTzbMQSfoso6BP7J6oYq3SSD6twHYCuVA0Z7oYXOCFhw38dZGRMAyFTAtykr2LPX36Ue+XZClMADY/5+bSegj7rHYNG5rwu3b/Xnng6BeFLk76CBfWn9trJyTvu5xITYLsLqbof7XUuz1Cy5sy8lKtW9fXDrjeXInhDx3jyUM=,iv:rdTaGopA/Wk9sGhu7HAeK5AnfaIs6MdEqAyKG8cmRKs=,tag:80BWubGAEcWFObxePlfcLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
