apiVersion: v1
kind: Secret
metadata:
    name: mealie-oidc-secret
    namespace: home
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Z64hu2fMiAZQ+rwuD2ud/Dj2TQ1pgSnIMNh3Ie859W6iuHuB,iv:7zR0zEqJvGp+RdxOUTuuMcf7tlNCigf92i9jteFLgtQ=,tag:h5Waq9t7vrfEq2GNJ6BrlQ==,type:comment]
    OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:NeLB8w==,iv:dNnF1+Lhv1u77HnVeuRBv+WGXa5IcjjxG/3QqEhHMX8=,tag:IvLFp7d22nuS5TrQhZ+TEg==,type:str]
    OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:5jNaCA==,iv:uSoLDdNAqUnYaOcWndqmEry+RfkIVOOcCP0mJvPzPQo=,tag:E4WhAUhT0jX1a3hBh6I7Rw==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:hD7PDbbeXuxmIuY45lY0l16WjYLWUPUsXFcZsu4HNgvUwPjvMr3wjutcf3yxFsoJdjZfGafi00Ow8h8MfDGo5rD4bv9fA5JcBJfGcWtVLYHsQdlpHluqposntw==,iv:5dF8q8UVLnGpsNeDltp3m3QPyH+GKMI3CSz/eLWkC0U=,tag:1B2ykpCcB153Z5qczZPSJA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:RQx0Agna4xFGNPA+KBg7NpUNZa7KyKmxyMvzmrtBnA+dFz9OFYKO9A==,iv:FzTxdjLnMZUQHgG/xklVUnT/DI98/HPULgxJc1vB/HQ=,tag:RzfcvcHL4FtXBuLEcTe8PA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:0KMr+rq075JOIMF3x2uy+prRCyn7hKCJPk+FZ18sOSsTXuyvTuTijYomEin/gCM4gVA6vl4y8kdG6urKJXMTX2Y9niAojAWWDuu/wtIjhbIA2Ac30jH28EtKDc4TLmxopV7Cs854RblYvgwAJ3VcpepIId0ENCta7duHv67xFqU=,iv:bsIRYsT3PjnR3SwmamJRt0GDn2+XQ94303NkCzb4pDM=,tag:n05W9ZF5pgcLxzp1i4UeHQ==,type:str]
    OIDC_AUTO_REDIRECT: ENC[AES256_GCM,data:3vIS2Zg=,iv:rLCkySqcs2gwlSaZ/L5kDFKUd7v8QuuEfP9K24tnUg8=,tag:/bf2iwbjGkAQN8rSg8O84g==,type:str]
    OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:vXsuXp/f3iIa,iv:k5jo0au9cUGGqjbDiW5KatuPWYCNWOYIswy2mn4GMdA=,tag:hgN6FvBie2m3uiplky3diA==,type:str]
    OIDC_REMEMBER_ME: ENC[AES256_GCM,data:2MhxnYM=,iv:M4EJJkPqIB1KzWI/f/TJCLKh8mCApMJDxlBJ4BbAdc0=,tag:PROi5BdL5vHxXa39CTpcFQ==,type:str]
    OIDC_SIGNING_ALGORITHM: ENC[AES256_GCM,data:gHTtJ9A=,iv:JeXhPOgg1VGk1WYok+INZ74bOOS7FL87O55lqVMwDO4=,tag:/9jGV4kiYQtNWiS4+wWH9Q==,type:str]
    OIDC_USER_CLAIM: ENC[AES256_GCM,data:2+21hsU=,iv:PHVGA4dFcVkDDAOqYN8Tm9kz/C72/pe5bihhX9ih+bM=,tag:kFT2mhvRWfibmQkFymJF8Q==,type:str]
    OIDC_NAME_CLAIM: ENC[AES256_GCM,data:3vf57g==,iv:5O/Hgc159lJSwGqwsUwSHVnUaSGsQCXQY7kgwkm4P0I=,tag:OsNveXtP1Ym6HUpvcTe/tw==,type:str]
    OIDC_GROUPS_CLAIM: ENC[AES256_GCM,data:1CFwXCb0,iv:t49QMsIYJopjAGJ994QsObGmsDHLt0ZF6pE5bVjFuW0=,tag:hYPqmgtSlx0eHwkYpa/pNg==,type:str]
    #ENC[AES256_GCM,data:KZcbuyd7KlMoaj9YeLj/IchS4v4nQZK+H/D6RaewtxS3ZCAc7dAhjnU1mlFFkdUloUbi+d3IlnfCo5n2cUFAwcNxS1md1VU1XdD3SlQgDy+9u2sF,iv:/aJXX97q4tLxbKa98PHAKhEe4vsUIWpdOd8Fc5Ij2vg=,tag:t5eqXyb3IMIb+yw8+iGgLA==,type:comment]
    #ENC[AES256_GCM,data:epT72a3ocB9HEI+d6ec3ePMRJ4qqKkvj+VLyHWK3EO0=,iv:lAW9XPMSqGLcrQO4fmLbrvOpxwVcetwyCkhtvvL0ZRA=,tag:D2kfADMhN3DNkjtem3Px+g==,type:comment]
    #ENC[AES256_GCM,data:G78rs+71K3EYieyQo0NkYL9RU1AvUxf2+DvQGXlDefe6Ow==,iv:lGEcpRjj8q55d8xbpHy6k5D6exykUBG4+6ePfqoaW5E=,tag:BXf3OREO3ErfGNgM2O96mg==,type:comment]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1dDVGZQUkJlcE9NclVr
            L0NPeHhRdzBVUVlSQ245N2NPZksrU3RmYjFzCkhCMHhZdEdqNzRHd3d1R2NRZ0ph
            MlZLN3BhbS9qWHRIeVEwWTZGMDhhR00KLS0tIE1vVTlTU1B4WkFZL2xjWEFydnFn
            STRiRzJvYWI4Zzd6U3NjYW8xS2NsWDgKscQykL4ndEAQos3gxKPvHAzTLxbxImYT
            gDprytE3FiKBS97iUMQJBIH0hHbnwFU4YN9TKnOxWlphUleOHiDdPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T01:39:50Z"
    mac: ENC[AES256_GCM,data:6tyKrpES1ocE5Hku6R1NB/OxAe8zRFmHPdWsJaBX1I6I42asq8zTk/Xjjy1kygUi9HQa7BWHk66eN37gHmYSuPgr6kBNDieWzWIPRU9vIWgrux6oOaGqlob6X2QBwB3pNssGjaXCIzUmZTf89+zTTn8PA/8DduAhhi9hwJ4ts34=,iv:aSt1PSaSkQ2oykrhv+ZQUrlrOyYC9lxL9gW01YR6Ts8=,tag:Sysq0bpXLTSOp7dlYCl2UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
