---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
resources:
  - ocirepository.yaml
  - postgres-superuser-secret.sops.yaml
  - postgres-cluster.yaml
  - configmap.yaml
  - helmrelease.yaml
  - pvc.yaml
  - secret.sops.yaml
  - metadata-secrets.sops.yaml
