# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: romm-metadata-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:63XXZYBdsY+aM8Oip/GMinI0YBZvgM2fOfyvyspmrILcGUp6bAlGkRf7hn1eb9yYoqCE,iv:gL9Dxr9EIVca85DGw3NftxJVWiDF6G452fp1aDzsEU4=,tag:QcExpJwPkROUkMJkP+x5bA==,type:comment]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:IWNbmGua8eNH1zap1dR9iDT/Ep+hTUxjq3SnzJfr,iv:KFn5KDWQcFtE4+X8RHt9nturcH+Tso7J5YJfYphCFTg=,tag:QU6K671pyTLhKWLG47ge3w==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:E3YWlsPaD5wCnWejslkDiC8O5o58GnjAtntL7S61,iv:+rlUOk0fdDBDfSiX2Hj0vjtq7+Oewy3WYt9lHzMbjA8=,tag:Ct7GagggxkT+9AqaAEfyaw==,type:str]
    HASHEOUS_API_ENABLED: ENC[AES256_GCM,data:wVCimg==,iv:H//vS98Bh91mtsxIVyZxU6fGG7O0smHlTW9/UhsxD0g=,tag:VXh1rXRqlgq4MmRJ0gxdGg==,type:str]
    #ENC[AES256_GCM,data:w/xs/EdcOzGz52vW33Ivuz+0S660+YT0i8UnUzSiei/Zxqr5AGd9NBe9D3XMsDz9,iv:h6JHjUjeIctLn7nCvoAQ2sHWIyABHZbPF4hh2GoFMH0=,tag:C9WU8zMuluutmtG/Yt74wA==,type:comment]
    #ENC[AES256_GCM,data:EokGRXOzMYFzqe41V+ULEVUJTTzbGQ==,iv:7txNt0D+asgax0GeEfaEsprS1Tb4V0888PWiL99Zv58=,tag:qLNCq0IktOjiGJiqUX9/4w==,type:comment]
    #ENC[AES256_GCM,data:tfBIQE3tj9K7ufpRVkWdSe3NHDxvQ9pHfeGWaKFDgq7lclJ52gss4ZqY/r/YeQ==,iv:r5dkjfnsQh3OsL0P8lVKk+Z0Mk38Pl9W3map4bd7u6g=,tag:qtQU3i4fpH8Xh+E9IQfMEA==,type:comment]
    SCREENSCRAPER_USER: ENC[AES256_GCM,data:EeDqA3sknQ==,iv:UF686I9gy2rJ0+C8dyGpzVsFaUSxCe7SNlYkw3V+tuk=,tag:mWxmQBj8ngke71RO5cViRQ==,type:str]
    SCREENSCRAPER_PASSWORD: ENC[AES256_GCM,data:VTreGLqJ0Xpa+uqB6+SEwFlTtAE=,iv:JlN5FFdw4EczOX9AusBb4zE2Vo0tWkm9u4OsS/LMGIM=,tag:kER2qnTI5Wgej32WxNWabg==,type:str]
    #ENC[AES256_GCM,data:h4cusGSBexQKTdaa+MafYfgsTgENicbW9ivCUa+8vGAP0WNznunqkQKQXgDaDEdByZmSdhAb2MqYJK1tWVsXWdit,iv:MjI0RwZ1hh+P4L5eesmj57XhDkeG1ZqBUgzHRgcmTLI=,tag:q5SkkdCvmo/CPwUY+ryjvg==,type:comment]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:y02cUN7HmPXGoLt8opm1EDPt1HNqzhtbW/OlpGNBIDc=,iv:OPLiVSzsZeyWqmmhfbcynvHC9H0jUHEyMnzCDsc9bPM=,tag:LqgtzqmmXSA9Hs5qaKODLA==,type:str]
    #ENC[AES256_GCM,data:xnYDaKQxTIGtixCww77yyNIfmxH2pSK/SMAsuRSW5xhPAG5glGyCRuFbaH27rEcuam3fZRvH6V9Poc9TdhNtPzqslQ==,iv:r6+yqX5sozSC4+mjb36b/gi1/fTRkkjgcYlvU3sm/rU=,tag:o+4CUnWG2JV+0fPLJJE8lw==,type:comment]
    #ENC[AES256_GCM,data:embbAH/fItdV4azXRTv/0gak9fhqtaYr9fcx9x3l,iv:UZ1e2aAYOfazXrQ9IRkjndZLG6AheMieE0KdhGYJ5T8=,tag:/x8ZjKr1xMth29Oa4smEEA==,type:comment]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa2w0enN0djY0bEJVdVRq
            TERIZDNXTXUwSUt4ZzdZSXJCSzhaaFpJekdVCldidkJlVHBTbHZMMW9reWRVWS9p
            RWl4UFgrYkV2RmozZTBJbmw0V3BlZ2cKLS0tIFRTcU1JRmQ5a2dDTmRQd1BtU2k4
            NlRXRjdxVWJMamtid3VQTXEzd0dHYXMKNb9z39EzKfjahnXJIvHcX7RvXOn0zDVf
            mLkWZZu7y9N/kWiGrC3s3B0g5qoaIR28HwRNMZX+8/T/Lm/e7D1Ofw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T18:24:36Z"
    mac: ENC[AES256_GCM,data:FeOkkF6QBEY4LZR32kUH42+JZ7krjzw531gCwBfPauyEd4mdgmw5t+1tCfMvQwky4/V8XawiNJ02Hv1J5mVkDRQLCYwRYgwEP8alXzlOQdji/PmaWHShQy2xJFfEgJWNh0NjbYcOgdVgRwkpvTFGlxiv3o1lav+nubpsX4lPlwI=,iv:pgqxSI8aX9o7lJFYrzhBiyM5o1ByRfFiEGr4+T8D01M=,tag:4XgAGNVXHz77/arD2LXLSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
