---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-postgres
  namespace: games
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: qnap-nfs
  superuserSecret:
    name: romm-postgres-superuser
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
