apiVersion: v1
kind: Secret
metadata:
    name: romm-postgres-superuser
    namespace: games
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:+wvQrbgu0ZU=,iv:pac1Jfhges3RTt1s2vIsRATNXr2v/J3x8tnFEgic/io=,tag:gtvD0ieGmtngnquMqA28WA==,type:str]
    password: ENC[AES256_GCM,data:uZy75kPJarb9VklsO98r5xgqCaSqqhjATRM1C8qCvm2C0WkG90MrHjkTNpo=,iv:UWK+QdNrONowKayiENL1S/qP/K71s0XvRILiyf36I4M=,tag:kHM0GDzOkqv+Pb/y/Xzy5Q==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL3hlZlNmM1hkbGJnZUlU
            MDlnWGVRYzFxUWFVRy8xdFpBdkRCVmxuY2hJCm1lYXBVSk9ZR2l2RlRqa1JYWHU5
            THEreXh4bnM3WjFrQ2tYQndheXgxYjQKLS0tIExLUzJGNTdxYVR1RTRDL01qdk9Q
            T1ljbE94d3h4enBpK3FBd3EvODVNbzAKVUIXu0MFjM5s4jjMAeALPA3QiiEw1L+Z
            z53eg/wqrskr5llOn0qb5bIHVtiKNTt2BPkxUN0ZPMjqvTyBcnPzqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T03:07:17Z"
    mac: ENC[AES256_GCM,data:CDrt28kBFo/Eh8KUbyujppCZsi6o43p5Y8xVlJpI3tDoUBTTCwG42ykQznnGSTBoOabKcsalvVsvQHIoMG6tiXf7aMRfsyHBE6OnuTVzkrYlKfILNnqfH4nuoPxGty02321MC0HIyqLXRHJWmlI0N1VlFIPbqDQNTmRwE+7mbCM=,iv:EJ1AifDdeshIdZJRDLv++NuwcNo0eqJwsXHU5YIBZ7I=,tag:s7ep4hoxAmxFdIk7GSnZ3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
