apiVersion: v1
kind: Secret
metadata:
  name: romm-secrets
  namespace: games
type: Opaque
stringData:
  ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:BubaPPhwE3YZqIlFt89XCeYQy8cOG47KPvt6JhZM4bF6ZfmQsbf6IQoEc9pht79bj12WI+TRKgkC7eAWlZ83PQ==,iv:dyROaQkn80XlBY3VK14YpA+FI1h/UtdHwm08aDnK3+0=,tag:gJpMpdzXUUBy6/pGv4xWjA==,type:str]
  OIDC_ENABLED: ENC[AES256_GCM,data:z3pfiA==,iv:zuVy9MxR/lUaKENxUyf127GFYJ70ASQCE0VGF+4lU3Y=,tag:DT79ieKSerGNfwXE25SvFg==,type:str]
  OIDC_PROVIDER: ENC[AES256_GCM,data:fFJ5hlDUOXXG,iv:OTDwh8zcU53z0+Fb8sbr5ZxUk1N353NVBUt5JB/4kDE=,tag:NMBlaL2Ca4q/xQD/101DjQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:rYTxrH391t0Fj3OQp3VsXH6f2o4krCW5pXjYG24qycKOUoVoAr5yNA==,iv:Eb5f4xElso0jFsO2xUm0NuW9W0DwcBz/jWOm8rwbqgA=,tag:Gj8UpaLmLdk9Ihn9UiFPPA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5k3vF7aLsE/fJq0QxOhsctmRNN3FnuimF64YPZnDhjeR2QdnhLtJyurD9du6HRfq7KjYtQVOr1rkHVW1Un5ym9oI9qWL0HAy5ELRmb879ElDkbe55GgXJZeaIEBsjSvEYH6bQYK85Xu6Fn0/9yRyF0DQdIVvIiwoR2B6zg1+qWA=,iv:M09OpcKnr3wu/TEThBjStVz8N+9jOo6ZYLzLh4f51Lo=,tag:CSk/D/e82VtFXsZvxA/eZQ==,type:str]
  OIDC_REDIRECT_URI: ENC[AES256_GCM,data:L5tY+xXmtC3/jlMDRl/uGO5vGuEgVyObsgkbmMCUWJFOO+XRV5bhdJROdJE+P6/ygA==,iv:Vaqn/rJq3GR7EL6Z39FR1zmwq/MDzGc3kg2UWpDdp3U=,tag:AI+vHjHdEsqpybbFEF9QEw==,type:str]
  OIDC_SERVER_APPLICATION_URL: ENC[AES256_GCM,data:5XkILbtkpfRsoixiuGlUv82yYQxSJoNzlTQjb5I59MFoLWWyKKtAxCtifh50gNBlYy+FLQ==,iv:MGhuvdDH9LkCsYM+7QQKenFADpLpRsCvHgOz9rPR+VA=,tag:d9rdFXMHOn9zXMz/V7jc6Q==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZHhkelV5ZXBEYmV4SnNO
        ZW9vbGFveVNzTEs3L2tKenlyOW1YYzRSL0NZCjdSb3BVMC9xdDJTMXpPUGJWRW5N
        ek14UWx4V240RGxwbEc5c2VVeGZERlkKLS0tIHNFYmR6ei9Pd1RpNS8vKzRsWXJM
        TjRWSVpGVzBmbHdGcmN2ekF2UW5xR1UK75Al6Z4PbgYBV2qydinHHpU7jw93oK6n
        5Z5ztKRjMMizCbKcHxlLx8qWi2uyu3YuJAMA+YRRXRT0rcGvLeo65g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T18:18:55Z"
  mac: ENC[AES256_GCM,data:2qhqdmZe6pfuKqaz1nSXDMMvaoHlNXKQ0sppKgZJVfdtjJJHWLjrsw1Fv9ikUa2P9cmO6nY315ggXK7dxIWA2FrG2f0vZhFIIHiG6TMQQr/iRpCTbSVRuGbuHp3jqVtkTCwGrWzSeSKm66uK7Ne8m3ty10L3Lz6iXc7UED0Mgsg=,iv:XUxuA48CAwO5npOsJkMCbUnifvtIFfQo2wjhqtuSePM=,tag:kDZlBrwpCSnNkoArLJnW2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
