apiVersion: v1
kind: Secret
metadata:
  name: romm-secrets
  namespace: games
type: Opaque
stringData:
  ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:NCfsXq3bLnAX4XgkeeLDc6Qb0wp35ni9aZHrdrUYDY2BfFE3pL0DLKKVJhWqt3EmbR1NuLE2PrZCjxS59QrIbQ==,iv:Sahy4TPlXgWkuiLVgLie/apezktVkkznJwCP8L/iZ80=,tag:2XoD+TZEA/vvERi0ZZ3xbA==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Qm91S2NOVGM4YVNMUzIx
        V0k4d3pMNWVNQUpoUG9ydTIyWWpBYVJTcVFrClRLY1k4Z3VIUWJtZ3haSXpMSHh5
        OFVmZjd6SFVyNzExSkllM0tobklwUE0KLS0tIERMcERlRVdyWlhscHNRZkZMWUtE
        a3M3SDl4R2t2emNUdEhFeGJUc3UzMTAKDVaEIF3sfUAFq1E0H7ST+hfmNCeUJ2jm
        RpgBYZBAaMtHnUDzQq5F1luvaMaxREK30/uKwafIZwVIhLkIZZD87Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-22T02:54:33Z"
  mac: ENC[AES256_GCM,data:Txl1DqNo+ynOi9qBN7OaO68rMxl7bDHe85Syp8BtAZ1tZgnTymN+mhzkKWIyntY6Fnpb0QVyuk8AyTx81ZGHq28jaB3Sgc1uCFA+e5x7v8SK0jViPuSF2MxMLQJldMQ918tXXjZFj0o2y3d++zahdWVa0PIwS7fT+zh3KfYcyGk=,iv:YluReOjhnWWbvjphRc78FZKu1PaQnzXgyUduGlP4YYY=,tag:VKHm4wBlmd/rtVS7ft9kpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
