---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shelfmark-books-smb
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - forceuid
    - forcegid
    - noperm
    - mfsymlinks
    - nobrl
    - cache=loose
    - actimeo=60
    - noatime
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: shelfmark-books-smb
    volumeAttributes:
      source: //192.168.100.180/Media
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-books-smb
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: shelfmark-books-smb
