---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./postgres-cluster.yaml

configMapGenerator:
  - name: grafana-nvidia-dashboard
    files:
      - dashboards/nvidia-gtx-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "NVIDIA"
  - name: grafana-jellyfin-dashboard
    files:
      - dashboards/jellyfin-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "Media"

generatorOptions:
  disableNameSuffixHash: true
