---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./postgres-cluster.yaml

configMapGenerator:
  - name: grafana-nvidia-dashboard
    files:
      - dashboards/nvidia-gtx-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "NVIDIA"
  - name: grafana-jellyfin-dashboard
    files:
      - dashboards/jellyfin-monitoring.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "Media"
  # UniFi dashboards from unpoller/dashboards
  - name: unifi-client-insights-dashboard
    files:
      - dashboards/UniFi-Poller_%20Client%20Insights%20-%20Prometheus.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "UniFi"
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: unifi-client-dpi-dashboard
    files:
      - dashboards/UniFi-Poller_%20Client%20DPI%20-%20Prometheus.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "UniFi"
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: unifi-network-sites-dashboard
    files:
      - dashboards/UniFi-Poller_%20Network%20Sites%20-%20Prometheus.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "UniFi"
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: unifi-uap-insights-dashboard
    files:
      - dashboards/UniFi-Poller_%20UAP%20Insights%20-%20Prometheus.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "UniFi"
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: unifi-usg-insights-dashboard
    files:
      - dashboards/UniFi-Poller_%20USG%20Insights%20-%20Prometheus.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "UniFi"
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: unifi-usw-insights-dashboard
    files:
      - dashboards/UniFi-Poller_%20USW%20Insights%20-%20Prometheus.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: "UniFi"
        kustomize.toolkit.fluxcd.io/substitute: disabled

generatorOptions:
  disableNameSuffixHash: true
