apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: observability
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:mmYM7QS8DzjnpX4vZmwWs7iM1xEi9bhrRBz1uPCFfeBbjD2u2K7LBg==,iv:on0q555+WOBrpr69tloEptTCvwjlt9xWD9jG0PCK8Us=,tag:mffSQKci7R6EZqOQNB+1dA==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:AVQ2icX99g7uMUjC7nVl4hrNNu7kKZi1P+S5NAYETFMNyD3QVVq8jRFnpo/jTLQW3L7TpjgHpwvjXc2Nk/5BhAIcSWCXFqARr00Mo0NWHzv6mM7SZi87sYixrKpg1hOWQZJf1LmCcq7ECyKrW0byph/+5oCVz5stsCm2R667xac=,iv:xk0ot+5NW9XFYLMP9lqVcr44qnnQj6nLoD17Y1QsV8w=,tag:/kt1sRo/BWfbHIIoRR71Tw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dEtwM0YzNlNBNjF0b3NX
        eDNwVUw0QzBMWVJybVB3dnJ0a0VhczVyVGlzCk1kN2F2YWg3UkJYaWVjcjVSUjZn
        NllBQjdkRUZlVDJDZ0Z0ck81cXlCTVUKLS0tIFE5dmExZGQwRUN6TmdUS0h6bGhl
        VXU3RlgrMDJ3dFJmKzNaZk1hSGlNVnMKsELMvJNlPlGvVJkBDcPI87du+a2NbGOC
        v/fcuoo4CcF+nLYa70jzbL3z+HNRnuJ3Q+7MZmMuUX+o/nCHrylXew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T14:59:51Z"
  mac: ENC[AES256_GCM,data:QAsLVSxqFmv0m+TfQuurcoUK501vzTM2iNVxdMKdBfBpTVApBkH7XpjBDv4peZ4WZayfpr7iZ6sg3IkDH6QtRpc31LC+yXhZiFNAuB9+F/yPoufBT2YIZyjYp5+PimGmVtBtmZk1MDSpVUULt/OVPwJxz3GzsgsnTcQfLOLzW+M=,iv:3bPpm8GNFuHfdYSL8Zv06mRD/0ic7EqJvc5/W2BSmOw=,tag:8tImX/kE2RoMvCIMKLDFgQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
