---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./pvc-mariadb.yaml
  - ./mariadb-initdb-configmap.yaml
  - ./mariadb-deployment.yaml
  - ./pvc-nfs.yaml
  - ./pv-books.yaml
  - ./pvc-books.yaml
  - ./helmrelease.yaml
