---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb
  namespace: media
data:
  01-grant-remote-access.sql: |
    -- Grant remote access to booklore user
    GRANT ALL PRIVILEGES ON booklore.* TO 'booklore'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
    FLUSH PRIVILEGES;
