---
# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30
apiVersion: v1
kind: PersistentVolume
metadata:
  name: booklore-books-smb
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - noperm
    - mfsymlinks
    - cache=loose
    - actimeo=60
    - noatime
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: booklore-books-smb
    volumeAttributes:
      source: //192.168.100.180/Media
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system
