---
# yaml-language-server: $schema=https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-config-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-bookdrop-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 50Gi
