apiVersion: v1
kind: Secret
metadata:
  name: booklore-secret
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:a8Xue+srNuxy2HJqX8ugsBz4N57fPOCYLnoXYoN0,iv:zftIBrjQsEHBpojKRJNnPpq4htz8dNmamwh9afcMCkE=,tag:peMZDVjJa36aK8HD2FJLlg==,type:comment]
  mariadb-root-password: ENC[AES256_GCM,data:1Gs4RhRMffuPxklHwZcT8AjCvvE=,iv:wjjdOS/mdKJ2i8xFxyjObhfkStfV7KGXLn/qGIWu7Rg=,tag:irPe6B554O20puDV2jaaew==,type:str]
  mariadb-password: ENC[AES256_GCM,data:Ra6ucYE0zkqE9JyjElGLezGaIhQ=,iv:/F0F0skyK0/OP7YNu30JC5+ztn41ev1iO890HWfUzVk=,tag:4OKMSLXvTKlqKTC9A40YBw==,type:str]
  #ENC[AES256_GCM,data:TMRu/8HRk8JnCIlAuvd+GHnTLyJOirDr8QI=,iv:+fVG77EA4FPcM1f6ZvYqaIGaA3mPKuwwJLiO888qGF4=,tag:CzXroGcwJu6sNLlOK6oIIg==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:cljay+tTHS6jyzey3QZ2tDZrvXCvZlJah3RuVhOJoaGYUfsE6OmixlJ9Ap/n,iv:X7ldYXUCgrKUwvJhc3Mao9mFEs7rhOi3udJFjDByZSo=,tag:6vRrlyQMp87qgenxZegeXQ==,type:str]
  DATABASE_USERNAME: ENC[AES256_GCM,data:FCfQBwqKg7A=,iv:YaerF04fT+XgEmZnkWWc7PkCuvzGzg4bzqaFsxh7fBM=,tag:5tMWGXgbDDhKNX6R4WdNTw==,type:str]
  DATABASE_PASSWORD: ENC[AES256_GCM,data:EpDefUOtZAPeCrqbQZA0VXB3lyw=,iv:ndgaXk4ursW7Cbq/3qGJylPYdidLnlZfwOYG/dU24+s=,tag:ejWV6lr3VSono42ux3mI+w==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVWY4T1h2WUYwcjhoSjZ5
        ZkpKOTY4OGhabjZrUEpRaE5zbHFWVVNDVXk0CkRkSCtjUi8xZm1uMHRqOTcwTkhB
        L1drWVROR0pkdXNLOXpiNnFVMG9CZFEKLS0tIGpvbE50NWt3UFk0R2lwUW85dEJI
        eCs3V3VxVmYxUnl4Q3ZRc0hhNnZkZ1kK9yJ53sKUYi0gnm/bVRNHUORB04QmB+ex
        l3J3zXftTM7F8fnFc3J8b1rntZ8O6jHNy1dQzSdPu9tyGLrxQuTNew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-07T00:36:12Z"
  mac: ENC[AES256_GCM,data:MpI3l26MpGlf7ChK0aAzlRDbePupI8/ILQAlmQi9LoBLwM1Oy1VIibIBzHecmUQ6RyN8uUmNj/X6NBTZOIW8JihW53nNUOOOkgWZFzh7UhFpitx5h/GVSXwc1fYtOXWw9IK5pN9OtKLs97fa1Akae8JtXeZpEvbCExXQAnwB+Eg=,iv:phivvCp4Iku8u/1KpdZasOWqfuMeVF73mFCWQw1HK50=,tag:LsvZGdZmftY2s18j8Xx9Sw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
