---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: soulsync
  namespace: media
spec:
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  hostnames:
    - "soulsync.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
        - name: soulsync
          port: 8008
