apiVersion: v1
kind: Secret
metadata:
    name: soulsync-secret
    namespace: media
stringData:
    SLSKD_USERNAME: ENC[AES256_GCM,data:Jh8roVg=,iv:+PX0649lE+60My+sgMmXuqd2Re8MpWMsq/o1IJMRin4=,tag:dsiojOm7c2Gdpwsv8EGP/A==,type:str]
    SLSKD_PASSWORD: ENC[AES256_GCM,data:Hlt3AonlUYrubY0Xzdtxl60/ViI=,iv:BaJZkwirO0zkZKWCsONNacB7qRyCYBKFe+2bexRO3Cs=,tag:tuJLAxG7rF6P6MoIxoEqFA==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRW9nc3FxQlZSRFZxcGg5
            OUh4cGxhWDVTWjdjcjdaYmlMc0h5L3FSL0JVCnZVaG9BMjNKU0JVMlZkaWhwMjFQ
            WVc2aEZpbW1ZNDhrdzljaU4ySTNwNncKLS0tIGlyeThUcWhMVk1jd0w2d0JiRzhM
            REVqcEdVWE9YR3lNeldleFBHSUlKUjgK9wqTiKS6i92c2WtHuFREFWYstkq8yjNE
            Ry4OI/GMLi4mdgcIYAxODzAQgEfCo1UmGmaY4V+QUH7kB9rWdXMcsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T19:53:33Z"
    mac: ENC[AES256_GCM,data:CTVHeBzfUHZjwv68GkWyOI4JwlCpQuu47okhtvja81aLTA2ufGBoy1Ww600S1JY0f0BzU0P7g3IZinRn76xnBuCy1afZrOw7w+gocvqsyfe2GVguLuIGeXGvsh8suQ9EHfltU3T9rZaO0gOhaRm1YI9GTXyX/PN6LRGLhe5y0x4=,iv:iIEfZZfKPX30LnurCn+zrvrGHS1EhM7+NiaHvpDON8A=,tag:W/ovvR+Wn+6I2bEyDNGOPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
