apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: observability
type: Opaque
stringData:
  #ENC[AES256_GCM,data:40X+CarYF6LgQ2ih6eUcp1F5cWIgKp2g5fGTxP94txNW3PKM7a3QB+Sk03mDyvEbCbEVw/f/gw==,iv:JUgalevHvH0iMSVuYOWijZ2O9k6pN4vHLZdirZWSHjk=,tag:Tjr1xMRJBkETflyFuD1GFQ==,type:comment]
  GRAFANA_CLOUD_PROMETHEUS_URL: ENC[AES256_GCM,data:rImVNN9/IX3hwFM1BLFrDx5ReMv5jKFbcfUAjvAi062NcH1rqZZwlIC0pWBNhBtNDf+a/2UKWF3rXeey0juANboMhw==,iv:rTW+DuF212nfeEZ/xGZ+DHGOLOTwwIcd6MO79LmMdDs=,tag:VI9yezwUdB2MW2sMMUhzcQ==,type:str]
  #ENC[AES256_GCM,data:+sNoHWnBdIAIEG8B4rTPpiBkb/rE/fspT2y9Cq1YKA==,iv:DL2IEt9afgEWoAxBj1Ub1rBljPcGX/36pyebz4Vnrn8=,tag:hpao5bDxiZuyAoIO2HsRWw==,type:comment]
  GRAFANA_CLOUD_USERNAME: ENC[AES256_GCM,data:7cK7qG+aBg==,iv:rTJSwxWjnZN3RDRjUZQNwh9cRUob1/1Ph1nKRSs5HnI=,tag:kOzfU9iJxGk7VK/6dkbk/w==,type:str]
  #ENC[AES256_GCM,data:xo18b2fLzWCVT/ucNK0zopHdV/MexAtkaFni,iv:u70Jus8FKxgcOui39wDREeQuJvA3AMRhTCUV+XI2Liw=,tag:NH4uWha3yJ5gNCYdPXbI2g==,type:comment]
  GRAFANA_CLOUD_API_KEY: ENC[AES256_GCM,data:ClP2QePQl92poRuRJws1mDbYsyC/jlYAhhWzHFldiEl3JhHxcKNNWGDqZyr2CiGaMnc4tSs3FBmpvpgq8uZo6FcJWeQn0Gbe4MfD1pdoNPE3e8grPqjtI1VcD27YQcCnty7EDtUrCVFyQV7NeJPFWw76ffF754ZoDVT8HTCehIhbHOYO+nDQo/pnrUh4dBJP3R9443EMEueLzHObJf7/2oBfgy8Ry3mrb+Sr/RxfXJ9B5IUj9SFP79dFBe8VFtaqyoY+M9U2psR76N87IPVE5e0EUBr1EVfVjFpnm71Sq6ZigqE2gt5yAy4ZhFo6,iv:5TTc9r1G5oArzv5p6RUghf/ERuK9QEpludo0zWJTVzY=,tag:0cP0W2PCD1SVskhwE7/Yvg==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYnJ4TGlHUVc5eWpUR1RN
        U1NoTlR4WFJLdnd2SldWVUZYTUZsc2drTjFFCnkzNm9GTjJIOEVhMEdla2Zwa2th
        clUzMUx1eUdML2huRmdUbmlEOERLbEEKLS0tIGpEczVsQjYwNVAyK1F5MFdnbXdi
        ZDZQRDZSMzZZRHFEL3BtZHZRemJQa0kKvVASxI7OKR0Aa9Xgyl9wzYF11zOgizEW
        Qo3n99G8rMGTEbvj3ma1eA2rrW+HphSXKEeCKKIVrCIMuYh8n6j5/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T16:28:42Z"
  mac: ENC[AES256_GCM,data:zkByhsb/aJEGpIS4E26Pd3ji345rnh+y7jusccfOxnBpvTIjPT1g5/8Ta9JihyBfIdROY11zW4NclX6XdHvBJ3+mrpXuD3/Ebw7eXNPKiqJGbG+/XYG+UjJ9dRQMCI9zUCvbsxJPvIVDxuua5+qD0ZlgebBqlmCAuKbLZqaHYE0=,iv:nSgRBwDRzBYKTyPd5kNoMuQRYWRJRvYGZgPVc95AzkY=,tag:kkuQ+zvA0NjOCWZBQeMysA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
