apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-credentials
    namespace: observability
type: Opaque
stringData:
    #ENC[AES256_GCM,data:40X+CarYF6LgQ2ih6eUcp1F5cWIgKp2g5fGTxP94txNW3PKM7a3QB+Sk03mDyvEbCbEVw/f/gw==,iv:JUgalevHvH0iMSVuYOWijZ2O9k6pN4vHLZdirZWSHjk=,tag:Tjr1xMRJBkETflyFuD1GFQ==,type:comment]
    GRAFANA_CLOUD_PROMETHEUS_URL: ENC[AES256_GCM,data:rImVNN9/IX3hwFM1BLFrDx5ReMv5jKFbcfUAjvAi062NcH1rqZZwlIC0pWBNhBtNDf+a/2UKWF3rXeey0juANboMhw==,iv:rTW+DuF212nfeEZ/xGZ+DHGOLOTwwIcd6MO79LmMdDs=,tag:VI9yezwUdB2MW2sMMUhzcQ==,type:str]
    #ENC[AES256_GCM,data:+sNoHWnBdIAIEG8B4rTPpiBkb/rE/fspT2y9Cq1YKA==,iv:DL2IEt9afgEWoAxBj1Ub1rBljPcGX/36pyebz4Vnrn8=,tag:hpao5bDxiZuyAoIO2HsRWw==,type:comment]
    GRAFANA_CLOUD_USERNAME: ENC[AES256_GCM,data:7cK7qG+aBg==,iv:rTJSwxWjnZN3RDRjUZQNwh9cRUob1/1Ph1nKRSs5HnI=,tag:kOzfU9iJxGk7VK/6dkbk/w==,type:str]
    #ENC[AES256_GCM,data:xo18b2fLzWCVT/ucNK0zopHdV/MexAtkaFni,iv:u70Jus8FKxgcOui39wDREeQuJvA3AMRhTCUV+XI2Liw=,tag:NH4uWha3yJ5gNCYdPXbI2g==,type:comment]
    GRAFANA_CLOUD_API_KEY: ENC[AES256_GCM,data:H0XK5JIgdBFNr9kuy6EQld0UEy9L/yzwB4huO+Mxo0dG1oZI21/nXKyfSsA8jDpiy1epzLaE7bkf0bzH3v0Q8s4AMURyADSPu0PCimXcwDGkKo7VHtP4SGKqqXUQhMHaOhTzsHIoc/LulGF0ELw08QZFZD+m/vwRCgGk/58M9pwbWbAcZS/+mAPA21uwu8iKs4hGT1xH9RgMlBJXsUHycADmxrdG+U4vmp1f/Gt7tfA6BN1uV2rOmFDBPhHpOCka,iv:ugUoHpVVe/BerI+j60AFBB7qDzGVRpiHhaHNRgCl2Ig=,tag:bR1SY2zEKT7ER6WMxMWWEA==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYnJ4TGlHUVc5eWpUR1RN
            U1NoTlR4WFJLdnd2SldWVUZYTUZsc2drTjFFCnkzNm9GTjJIOEVhMEdla2Zwa2th
            clUzMUx1eUdML2huRmdUbmlEOERLbEEKLS0tIGpEczVsQjYwNVAyK1F5MFdnbXdi
            ZDZQRDZSMzZZRHFEL3BtZHZRemJQa0kKvVASxI7OKR0Aa9Xgyl9wzYF11zOgizEW
            Qo3n99G8rMGTEbvj3ma1eA2rrW+HphSXKEeCKKIVrCIMuYh8n6j5/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T16:49:13Z"
    mac: ENC[AES256_GCM,data:7F1c8eiE4eIsWxJV1voC14W4NlEPFpTh5/2W0NdfXY62o0i4hYBQdGRNkLxEKK7l4ulvZA9YEJogYT93kbXt0EWbGSJRZ7cegFIURH3yxUlbzSv6s0Q5dogLug3CnVJ2yU6d5+SrC1w0L/rUtI7E+7Im0S2hs7uf+NER5lg0S8o=,iv:N35SCjcRmwrBCkM+8XG/AP/QT49qC1EdOegdsDs9xyQ=,tag:0sOGMi3251qnY51v332KiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
