---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listenarr-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 5Gi
