---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos-smb
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - noperm
    - mfsymlinks
    - cache=loose
    - actimeo=60
    - noatime
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: immich-photos-smb
    volumeAttributes:
      source: //192.168.100.180/Media/Photos/Immich
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system
