# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:ymXFycM0vf/uKDsBhGxzmnd2lJPb6FDLJKthnQxrqoxmqG+e0DZASO3H9DYKBLnu7Abba1x1FabYFVL4kmPJFESWauLc/q2Fj1/VyVam2OeBOHlYKYUiRridYZB0Co4btaNmt6IGIZpv9Y611sp1d4F7VA25osvnVDHefxywyQB1xaKYeovz18BOTqkJmVCnUi9Hn/Pb4XSoA1NhixdPBB+XMuHyIC0FlDsqFp9w5v8uon8Z,iv:RIMm0K6FLceJ7Hu3mdgA0oxwQSq++eWTlYJRcZ4X9ZU=,tag:55PaE85EIN10ldgkSBWpmQ==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUXg2NGFOaFoxc2Z5STJy
        cDlscHZTTjRBQ0RLUFNLQUp6MUwrbzRKbndzCkMyaHJ3aldBSm5jQktucDFTMnVu
        NzR6ZTRPdVNncEJCcWlVS2Z5djE4R0UKLS0tIHNwS1o5T3o5ZkpsSGhodThCQStY
        UVZWOGd2Yno2SklnY1g1am1wUURiK0UKuwUw/WuxWfyHnX2rrW9GPE5PNw5rl9t3
        rKLRUdN/YO53jqLUtg8rUPUTw5Dv0IVqlwXVEJgmvUcQ4R8GQIS2Vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T02:55:45Z"
  mac: ENC[AES256_GCM,data:OYY3pXSTAzbAX79fU5lvmb9aqCOqX8fl1n6fSGK/LhXDLlR25E/k/tt1xkd0LAGIWVL4J8aogtLVlqQbbbxbV9JjTl69xrLlh1QkWoCdyJvsceS2Y0o2D19BG0EbBn+LVG6MIQM1jRXbRnbhNB9R/kbQ+SqlvCKe3/lRg+FL1bk=,iv:Xc7tnCYpu8v8f9tvfsHYLyn2YMYiPxiSTZQa0Z3zH7o=,tag:L3c+Q/I7R3xuj49QXzjB8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
