# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:a66WjFJFJVFe2VGmLzwV4aIImjnKBjPlmOPnM41/QInzZ9rDA16qEMNeioZCfQZ3CbRBDxYUOB0MkGArJo/B2o0oo57FBEFtw18NBQRyqcJSequwkNVqUneBCTuTo95Ms/4ISuKxotX1+6gny9RzVUr+SCJIcgXkNNzDUTsZ1DvfU8SkS4b4q3Z/45/APR3xFL0zs5NWcN4pDMbBPKRW4O1dSNVYs3ylwBlflh5pVyi+lN5Q,iv:AmP/hLPuqZlL+5eW1h1l2rPNiSTqBHbYKazjN5eWqcc=,tag:Twx3wTAkv5Ufln3D1SF29g==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDLzh3aWlqRGVIc1hGdmxi
        ZTlXWTU2RmJwZGhxMGFraGMwSFVEMm01SEJJCjJ3SEl3TDBUcTJFcTNpd2NCMEFM
        SXAwS3MzVHZuYnJkN3c5MmdUZTdYUk0KLS0tIDY1MHNMdVEzbTVycXpwNFJ4d2gy
        eCtKbzVnbmNSSnh2a0dDYWhFY0NhdDgKZFY69e+/804ioTWbrBL0l3tQRjjpFBYr
        pRN8yO3U5K62VfWpaRah8+dHDlDBEn4M0yat/PeiMxALFSkGQiRUWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T02:21:53Z"
  mac: ENC[AES256_GCM,data:ZAaOY0o0GTvwobirv1sPouDGpzLHrSNDDfFMO0KF4klTwc6asHr7yv9v5nHnjOQqTyAAs2LJlfeNv91hs4YGl0tYuHTmpQUgQmCnr2dI3/5tHhnEsGPYWzmDZCiZEVwjNV9mujWX1UFimmXRfNt++IflXVrBg9lR7qboIwZgxIw=,iv:4FvFU2gnCF/jcBfHU8gHrLn6gljhgZEagq06lQihsVo=,tag:TI7AIsZHYZ6H7fqwNRsE+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
