---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n
  namespace: ai
spec:
  hostnames:
    - n8n.${SECRET_DOMAIN}
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: n8n
          port: 5678
