apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: ai
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:pNbPvLsT0+p/W3iTcAxl84lSWyKoVl7IvxuDBNp5/fegMGpZgOmiM0mvM+w=,iv:C84SYsXtoxynvH/zpTh9LNgvNDOyGc/u19OWSpCJWNc=,tag:mprER0zlHHvfDQrx59TuIw==,type:str]
  N8N_BASIC_AUTH_USER: ENC[AES256_GCM,data:cxC3Iio=,iv:hzXgS3itnBzISGuKpBGaTlG8dfN1GNUdgkHkhqadlJg=,tag:0ibh0f6rUMPE6nTrbG6cdA==,type:str]
  N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:eljnT7cLGEyNrLYvS+XyNnvJ8iMtT21TKl1F79MkGo8=,iv:OqSOCKWcHb7RSX/aDE49Lox9/rUMrGf5p7vElUUIF+c=,tag:v5dkYc8fVrYZCsdD7rQWNw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZXJWYTgzaHlHcUgwNWhX
        Y3BSTnhpSXlxd1FIL1p5NkU5eHVqdnZHUGxrCnBmeGJPbkV6a2FSS1VvcnV4Vkpz
        OHE3clZ5OE1OKzJnZHR4bjRPOGZ2RG8KLS0tIDhTS2JoR0xLOTZkWFFRK05ZczVu
        bHgxQXdwcE91S1E5WXh6R2h1ODlVOEUKq0GwP/4hAyoVtmMkw8/1LzIl3xCaV087
        O2tFcANBPQ9g7/rP0Va1yoPleGxWredO4eQs7yiZg8xgr3IgM5vW0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T19:57:14Z"
  mac: ENC[AES256_GCM,data:M+fpz7Cu7LHK6Sm3+gR3AWwKCrbmLOJ/M5BhJ2483H1tMSdw5LArzU9bYplbVFM+bqtjzXR2WRAYAAWE1jVW5pTIaGfXmPNGGsDVm+EL/X8ipeZUphqOfckkvKvRE4V4Swve7YzWyk5KYGPd6n8ezBC1ihKAFcostxTPYjsFxCw=,iv:OKkNoN2FeCpmxZyjZr+D7VbugN5IbKW1y3wQNHa6LuA=,tag:gdYgyM7Tvo6iPEdvJClrWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
