---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./k8sgpt-operator/ks.yaml
  - ./k8sgpt-operator/config/ks.yaml
  - ./local-ai/ks.yaml
  - ./mcp-context-forge/ks.yaml
  - ./meilisearch/ks.yaml
  - ./n8n/ks.yaml
  - ./ollama/ks.yaml
  - ./open-webui/ks.yaml
