---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-nfs-db-sync
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.100.180"
  share: "/talos"
  subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}"
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=3
  - rsize=1048576
  - wsize=1048576
  - local_lock=all
  - noatime
  - nodiratime
  - actimeo=0
  - sync
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
