# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:v0+ThbDKvZF31NRo9pn5MGctIqCJ3Y9Ezji8TmeV9Ki/Jwjd266BLQ==,iv:V0ufigb89u0Iu85cRxxvsEDf0pFURuj0+4yxXQruMFI=,tag:BRN/qq39xnbgeG8GKD7Bbg==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcHArSW12WWlqU2cvZXF4
        d0NLR21Ubmh4MVYyZUphd2FyVXVqRStZM2xJCmpNNWlZM24wVU1EN3pRQWJ1d0RZ
        YkhJUFkzb3VKV3MvUnBQYTZxTTEzbmMKLS0tIHFXVHpuNEtuSTZxVzRCSWxheHBL
        LzE5Rm5sVW9rZm40SzVFdXh4YmZta2cKdusmxD9ZVZBKupd3Pa7BoLUNh79khDcp
        WxsxiBLWVjv1AXrC6jooQWv/Pc3g3FW9RySuWceDqxtZKRyjroRCcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T02:55:45Z"
  mac: ENC[AES256_GCM,data:xEIl38i+x8l+68gKejzuO7lVX769cnm1W/GyKTBoklZ5KLHGu3HQ8WhBfgSWwQ4DzbSyv9d4NtH4zB16a2+VZRynJIminihTPLpsGfJEDwdXfJStU8GFnwcp7bBRCXTe8wqGrgdVYkZBWEKPTGqgvQxdtW2SHy/cVRVkLk4kDwc=,iv:yIYSeZA9k9K8ayGZxhFHmw8P8Q2TgGcs45ddOsXyoGI=,tag:cXv5SFWKhcXXMOiAq4Dljw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
