# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7aTBqioa2JbmdS2Wyu1fBQ4dBRDxpCc6WEWJFCuTAFGWfWynHQAcjA==,iv:y/tN57LGE2k4RDOMqtASaUzHN1csdDD9ZvLWFnrbyvg=,tag:Ku7X/El83dCJp3uWzR+Kjw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TklJdEp0amdGUFpHSmRN
        dm5oS21ZTVpHZGd0MForVGZ3SS84cjZxWEhjCkR5T0tSWVIyNGo2dnBkaWRiL0Zu
        NXY4aW1yS1NmNk5PQjFOZ204QkdzaWcKLS0tIDFtcnhYSzlaTC93MDlyRTZKaEoy
        WTRhU2EzbVJwVHVUQ2VxYlpUQUNrcVEK7DEhAlURzffRVIIBtqGE6D8E/lD2GEOZ
        InzBKCra5vcnYvVe/i4TdvO7xX5BcMOBDJ6VmjjSkdBdKqRKTiYaIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T02:21:53Z"
  mac: ENC[AES256_GCM,data:3+ScKYpxCj8mI5/HuLLt6R4jF91ZUSe8MLFELTln0Ifq03yT48Ou4LiZtX3rE3mB2BY+AT8Ktis7UXWa4ftJ9seuD2X3XfPpVVfmfrp1sLqVRBio7Z+7fbBofQf5yLdx3I9FRQGrN0M+23PKImWn25Icnik1tTvpUAjdYEMSfzI=,iv:qYM7xJNfsp2UK/9WAiqaiGkt/4SesETrqqtZFEIh/Zk=,tag:nraK0zSa9zJ3Et6DeMb/1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
