# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.42.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.42.10"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "tuf1"
    ipAddress: "192.168.42.254"
    installDisk: "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_M.2_1TB_S415NB0K303452A"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7ea205866c6d1ee573d93a4d40a23dfeb20cb38715ade24583eb9ca42cca538d
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "24:4b:fe:8d:e1:0e"
        dhcp: false
        addresses:
          - "192.168.42.254/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"
  - hostname: "skully"
    ipAddress: "192.168.42.253"
    installDisk: "/dev/disk/by-id/nvme-Samsung_SSD_960_EVO_250GB_S3ESNX0J931509B"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/5323d5cf13809e2260e475c0f46ff06a9be7afb806804beedb412cfacd7eeb2d
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:1f:c6:9c:aa:11"
        dhcp: false
        addresses:
          - "192.168.42.253/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.42.1"
        mtu: 1500
        vip:
          ip: "192.168.42.10"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

