apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: observability
type: Opaque
stringData:
    up.conf: ENC[AES256_GCM,data:rlcTad8IAANVA/39bBzVLrmQyh/BnIV1HDylLDEAz4AJnhV+4krcUKmu85a676GxZl+TU5pPweyxcbZ+bKszKQbVFOcEs2dgPhs0LIjl5OCPjkhKJbt3LjbWT6WfsAXZnj1PB9M9iIPvFe/MlI1YLKpLNMGLbaQBY516Nkg+SXPAbMocOqn68B2lLqSNmFhO2UTc4p/FkiiV/4z9gWLvfO05TS51m8yuHnC0i8wFSHxWUKTOidEhFjOLFK2p+048kordlb7I50yBSdGofd31iCY9MAFUXN1yYJjY0PQft5DGVOlKpH2fzRWNyXvWBRmFUf4t/i9F2R2GMSaU2/uOqf/NdressR0pBDBg20T36+QJLFknSrm4p3YwvGmL+a5GzPOcvexTl9Juuhb8VIhIicD/sXiCpD4t4XyS1x1YaBpetQiMjgoUPXLTbzurA9HUVbilZMN+43wgAsk6ebYldLyPWFCgWOBltzo4AZ7Jw03JA5zprUk8wFiAlGgCxPJGA9AnQ6nbBioDlTHHS3BH4owFkWxdUvBJkWlLa4eqlbgiUuUq8kM1FnhPR1V3x3iK7daEy7P0D87TvKH5QS8RRpJGh2i6b96ikHyPd7FLDoIxXo3J+qGNTDuqQ6JQZOKROhlg9Joe1v5GzvmNAdAlCNjeGb7t6lO+EW20NWv3E+jIJMzHtT1AuR/zrQGD,iv:rzTYYxdK2868/Lb11u8F5NCR3Ep88ZO0CcwD6yM9oTc=,tag:2TVPZ3rc1v+l99YpmYU2dg==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHJVN0M4QlpCTVQvREdK
            dmlzd2FCcGtMWUNFZk9MVUFwdXQwbWdGemxvCk9VbjlYTTlKQ2EzNUdjZnhBQWgx
            T0VNZkxqang0STVuUDFJMWNETkJjM1UKLS0tIGlURG1ubFFSYTVUOVp2K041Vmti
            RFRHczI2bmNUUDBSYzAwTUcxeHI1dTQKN6+WUQSft/JBBPx0As2sIBgSH+6X6VZF
            QIfgq6TsP03RL7ZfY3gHFL8J7SJoJ0t8lD9ZAx2jqAw2wyDRwUfdfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T20:17:24Z"
    mac: ENC[AES256_GCM,data:7ftA7yD5hr6CaLOAHIBeskG5Va3hTciasrx6KVvcKqwtkTt4hRga+0EUX8LJ5kH3YbFxX2k3SJTrKPGvRv4sguiAwFzb0hYNH1++zAnX/0zGCKJ2Pjbn6ebI8azRfroikH/BuS5EeOE38Ym7wPAa/IcuI0qdFxDhP8piFL8RC0o=,iv:iAw8ZT0ZFbVkOtO/7+GAxrRahHI9jfkRRr+tGZADCa4=,tag:KRvfk+Vc0+snoZXDPLTFpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
