apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: observability
type: Opaque
stringData:
    up.conf: ENC[AES256_GCM,data:PlkmJxglnG5wdfzqnFn0o6WclTPykj7e6bTt8AMz+1FFjfpNKZxO6CbAKipOC805KE7E/42rD/EVNfLWElqsVp06cSkDGKkpUKUnORc0xozywGektFzUnyxFcfk9AOIC16rze05NoPwYrrbSmV7gakiQYciW23YzGh9lA5cuE7r6QSsBkRdC2KPa/bQhpZXWkAFN8+VvkggX+eG0+cs4qAGYP+/TVYTnPFhPRanS2nMuS2rJtpFdRcApgLPm5uuCP2TI8W/gezErZUMYgJXtoiZqaHf1v0ZfkEHoKE3hlNLwKuP/aGWJddCoFhXB3ue/rxW+uQlsjGzwWI4h0U0/MgVOVlPLDqFJ4jmKbIfEuNvWTzdamrHrz83wXuS6vjqTiMBYyBG3M1mffgALId9xvG7CN8yuj1EodVgz1uk9SOXMjsMuDcAmdRYuVit664qA/cygeIyTQto+1v0nhsYgTPPCfeefaXMzynkV+aY+ofXGzbJAkhK0Oiuo+JVA1RgWK/U0bu6TB5pGEyjD8/stI5uvXjW/3BKd8B/u2J6Sw7hM+n5hrUSYj0Gl5UvPqJphm7LXPpLhomVBP1Do4ouRhAEhHJ8QZuDszLA+waZWcc4XgOgm5ZdRwOBj0pkaCaVCVnsMtmaYmbp1ARNnwDdUauhCkZvW55esyDyukIZ0MShlaCM2njtwkxXq5g==,iv:kjyu21YnpHuPxlMuh4MwGrvkFDE1Uao1iEgCYf+KqUc=,tag:DItUc6Rimb9sWSjF3EDwhQ==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHJVN0M4QlpCTVQvREdK
            dmlzd2FCcGtMWUNFZk9MVUFwdXQwbWdGemxvCk9VbjlYTTlKQ2EzNUdjZnhBQWgx
            T0VNZkxqang0STVuUDFJMWNETkJjM1UKLS0tIGlURG1ubFFSYTVUOVp2K041Vmti
            RFRHczI2bmNUUDBSYzAwTUcxeHI1dTQKN6+WUQSft/JBBPx0As2sIBgSH+6X6VZF
            QIfgq6TsP03RL7ZfY3gHFL8J7SJoJ0t8lD9ZAx2jqAw2wyDRwUfdfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T04:22:53Z"
    mac: ENC[AES256_GCM,data:WCPydmeA2/5EA/v3vN3LopfJQ1Wxpqr/y0SnXJA2OTLKRrZp6y8FQZXzH0S896mtXP8duAcFuMpEMn4enPo5fW8SFs073clrvRbnUDoXQAyKl+N4ZF2CzzfPyrJYgYPaOLS9PytQIUOKrO8IUopgGJb0GQruJcv8yVtd41t711k=,iv:x5hblLEE4UMXvIqJez9kc5d4OpIJ58RnP01ovCsNf1g=,tag:pT5cm6vhEhUItvtANIlxAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
