apiVersion: v1
kind: Secret
metadata:
    name: unpoller-config
    namespace: observability
type: Opaque
stringData:
    up.conf: ENC[AES256_GCM,data:uX+PqeS3OOagymEqqZwDFPucQWHuH6x97WbhLueOLzx/fakc6AzHr17XZcSxmjx9t439+mvaZbC1k5u3GxNCGMPy/ccfRq+3SDOhk9X4J9JiPmhp5wW8caU4989dX54dBFnPaS/whnUtZdFu6Ayy+XUAxu/4fVola1iECV9UyVZuV/PTelXk8bySddXW8DamKXG8EQTtqzENxhWsKH5yTPCllSPkU3Pkku+ho7OnO+WzQZ1Z1Psk9CUFrLOQkbu9B+Z5yL6nFQpRagCvPWdgLtBLJwnGzCsREdc/S2ohEWDBBb+oIUQufA60sY5o6b1WscpaHM0oo3BKx7gQTg0wW1wfuNjbx2ftjXQxHEWuUCT7IMfZYjUPjAc3H52y29yuVLM8/KF8a0BWux5QTVb7qSQ9vQCDt7YLNheNq/zXzqMn/+JsZ69TjHTPCMXTPY2g/tbqOv21cIQVivf/7lJ/94Bc9Oo+yDdQTqQ4uDFfjn4hWThhvQ7hg9iBTNDw4ahHImJYQjUjwRBJkgLccenMH4BhRZA0G+DOAgPZuKjYPxNlLHfXd58r182uK3U5YlO6kRCmoUnrhJGIzna1ZfOgjYMYBjHGkakepReypq4giGhJ7hl3YhziyWpOa+NXsRy2vJthHgaXstY37UEpX0WRXNwd34JH6n0Wmx2G1Bj2q/j95LXm5OC9SGxPkCqCpQ==,iv:WAeZDJUZmgMfkg1fhNjSfHpGL8gMXKP7E/eYkG9h+/U=,tag:QfWOaLo6vhqyzbBGOYKe6w==,type:str]
sops:
    age:
        - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHJVN0M4QlpCTVQvREdK
            dmlzd2FCcGtMWUNFZk9MVUFwdXQwbWdGemxvCk9VbjlYTTlKQ2EzNUdjZnhBQWgx
            T0VNZkxqang0STVuUDFJMWNETkJjM1UKLS0tIGlURG1ubFFSYTVUOVp2K041Vmti
            RFRHczI2bmNUUDBSYzAwTUcxeHI1dTQKN6+WUQSft/JBBPx0As2sIBgSH+6X6VZF
            QIfgq6TsP03RL7ZfY3gHFL8J7SJoJ0t8lD9ZAx2jqAw2wyDRwUfdfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T04:29:33Z"
    mac: ENC[AES256_GCM,data:aK78bFYsiYarzZBPeX+2wl0BwqMuLzsWqY7WqZmX33ueaDS3xFDk9w3GQxdZjmcLlQFM4kKn/8C0fiu+qiGEHF4GmpNbvnvMs/IAsd1Wj0xSZ/4hvS5wHfJSdsSCgEys8AMzyMbCRsLDxNmKerlTWhzJ/hU33NCE7bu/5eK3lo4=,iv:XLRbdAye2bihc3w7OWaSuuHd5uapnCRR6fbSRKKUj8w=,tag:H9+ZmnXUYEA55YBgu8EDAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
