apiVersion: v1
kind: Secret
metadata:
  name: unpoller-config
  namespace: observability
type: Opaque
stringData:
  UP_UNIFI_CONTROLLER_0_URL: ENC[AES256_GCM,data:1ZnYGU9qXUnrWKBOFRQdgol3qPaK,iv:+NtvIAPWelBcPy81zuuQdrbWh7nVW9Ii08k8tHMEF6s=,tag:/o4fzvdTI8R9nxxvJbcHBg==,type:str]
  UP_UNIFI_CONTROLLER_0_USER: ENC[AES256_GCM,data:QjE8/RNYYTjybHg=,iv:d3vzM0mD1xzZ+w52kVAKQsdWLZBCRsGAUquZjhUfmz8=,tag:4hmACMdIDizooGzKONthMw==,type:str]
  UP_UNIFI_CONTROLLER_0_PASS: ENC[AES256_GCM,data:QQZQaGGFLJPJlc1OTDPz5JTmCDVG4kXjNVP+d1OcIg==,iv:xI1jl3QsqkOlLjXroDa5JzNzI2FLJC9odurPjXZOzQ0=,tag:FqIxXVQAN6Em4Dc8YlYaAw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bUVwTkdFSkZvSWZJZEpK
        U0sxK2tTWTd2OUtMbjVzN3Z0Q1B1RS9jM0hFCkVURDVVQ252ZUhuamVXa1k0V0VI
        cG9FVmx5Rm1EcjgzblhmWTlhOFIzOVEKLS0tIG4reE9IMVFuREp4QlR6OHpmaUY0
        NnhYTVRQbHVXTnh0b0tsSzdZZTRLSk0KsTp3x+Cj7LfLoo3vzmXCS2g9HK8POVlu
        pCqwX/LFO8S1ZElSNryLsKpkUyhj1ZPW3u0n/avXXzeqyOA7wQ6DZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T20:54:23Z"
  mac: ENC[AES256_GCM,data:haS6hknxHbiqNPwWUI3ZweUjwU9+X0DpLPqojjo23YaYaKPMxNuSgOd/rr4NtbFz4LzEZ4dnbXlGzqMtQkzObrSMzLQ26/ALyBYbL5n0jsuitI5tq+75iwFFhlUJU0cVv3Dk3RUB2qRAS/fFSojfOIhuDjIMB2ZDSbi3aPMVRug=,iv:qeumcJfRy8tXZOPt6YSK+LXMr4G7C5xUkcKzGn4A4uM=,tag:62PnHLvkSSwbvusmjqqABQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
