apiVersion: v1
kind: Secret
metadata:
  name: unpoller-config
  namespace: observability
type: Opaque
stringData:
  up.conf: ENC[AES256_GCM,data:cGyW0mRWjgKIJyl8r3uMCxrhKJ8RpVLBBQr3mVLUHzHg2oMQ4KPHpS/idbqPUffjyoFQyXSr35tQ2QqUPILf/gN8JO+4ZMnLq/5AwpNmymKM9aUscHbjDZYfcBZMBjN4C/v3znR1wxI8sYhyDhh9nF4GpmbaVg4sxf0ykvz/TG8EjH3KyUmIiK1NFi4mrkImOhguQC7ExSoKEzqe/22AGzzDphwa+zPDVsrE5mjakxx/s5MWi5dKXZKWAClmR83wqwwr+zex4XM89pwh3GDCCLadvUFLiFJGzgLmpoVMylX8BVmuoFFibWmz/MghuwqkqNafr6NqF+lOXGKah/PUzSqEIGAC0BcQ9Td+A7IZVimktK2iBe1OOQN61KowGJYL4IzUm7ZbWpScPFhw7rrB7I/xKGtVP9D6bUNj+W9WdA/uqs8wDnIgsvfu1t+l/7e07EHxT0C5WqnalQokd/bLKJzl9eXy4PRDU1ULUtt9W8PhLmjgras+2gmtjUunR0wr3Q4c8ajPio3Rrzh4lW9ebvx8UbAsap4+hBQPUA6rFGo3c6PVim53H59eDKWT6vEZ9AvM0gime4gOOChj5xtwAlQ8NgeNCawWBUEjIpZQdDc/lMhpewBsGBjpLxtqNZLoxe0ZfDMBev2hcyGvRWaF9LEgn9PZfpDWPDAmTueXIkAS+WuJ41+Z1a36vq2rc2oY,iv:kN/vF+KTkRmjkNBSA+xGb0yR7nw5xjgdFTJFd3OfMBQ=,tag:iBWKEcFpM7gmk9TR0uDCgw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHJVN0M4QlpCTVQvREdK
        dmlzd2FCcGtMWUNFZk9MVUFwdXQwbWdGemxvCk9VbjlYTTlKQ2EzNUdjZnhBQWgx
        T0VNZkxqang0STVuUDFJMWNETkJjM1UKLS0tIGlURG1ubFFSYTVUOVp2K041Vmti
        RFRHczI2bmNUUDBSYzAwTUcxeHI1dTQKN6+WUQSft/JBBPx0As2sIBgSH+6X6VZF
        QIfgq6TsP03RL7ZfY3gHFL8J7SJoJ0t8lD9ZAx2jqAw2wyDRwUfdfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T04:19:14Z"
  mac: ENC[AES256_GCM,data:GrLOr4jnkISSIanfShy+8KgqrxOlWbL8JM3NBZP/NoaxOIe7EQ0a6i454/+Wbn5x5HDIaHUdGExUy9bydCTxPpa1lwgwprfdELmcqXZK7HZr7lm5fu0yx7hlcVG64Hd8q5TW4YSBs33XecmzjnhXqjycqMASrgbpgazk+1liJh8=,iv:Hb9gsGDPIOYjcb8IqO4UmjJxb6/MhAsi8z+QJvQELFU=,tag:TLvAbrzb6IvW0SVm31UYiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
