apiVersion: v1
kind: Secret
metadata:
  name: unpoller-credentials
  namespace: observability
type: Opaque
stringData:
  UNIFI_HOST: ENC[AES256_GCM,data:ASj++6610V7ejBo2EyJjv8zk6LuGYg7Yfio=,iv:RO4y1eLr6bxaO5QYjJRQEd/PI2tzb9MzaLvTBrCn1as=,tag:dhIgpseuNYY1oFCaXXnRxw==,type:str]
  UNIFI_USER: ENC[AES256_GCM,data:zTrgD52eo98=,iv:Hx8+tbYocqxPi4wGzMbzPjwT4LQkswrowiO4YdQZ1b0=,tag:i0iejAVkOVWBU3slPSYDBw==,type:str]
  UNIFI_PASS: ENC[AES256_GCM,data:Bnra78xXnZx0+Uz4d+SkyOYT+prgmT9KmNmCKmGQ6w==,iv:wJbn+M/Iejqu5owSD3z22pf0rQt7MTsMvnmXEruOwvI=,tag:N6MIqD/cgBlojnbZ62aJug==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleU1iL29ZRUVOWkdERHpT
        V2lEcTNEVmRudTJxT2hiWmltNXZnS3J3b2lzClliNVBINzNQZU5DZ2NIbHBYTHND
        aTVtQWk2SzcwamlIa1pRMTN1eW9YVUEKLS0tIFZXVVJxZnhZQjduOE9ySmM1VEpr
        ZHN1MXFzNVhvZmh6UmtZaGpDWDRMNVkKLEdp7Gc1aZi35NznU4x0e3okW5KA5FIy
        0BILhlsoFO7H/n9hhSivh7Uzsngvny2lQBdVAYeMzuSQ/CwlYjDAbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T04:02:28Z"
  mac: ENC[AES256_GCM,data:kpVFsjiGXIg95K3mgF1oidd9HNcSjxYORNeFjglsdCoAJdkJl96rkikS4iyUMs2Ob8roeHv0fmpCWzm0wENvOcTzPIwxyNSTZbmfKFZRb8WXZYz4gNuiLvOVWbrp+cpaQkGUguIX7gJg+SiEqYJ9a46SKtBACj2SwkKedzNCjbQ=,iv:RsFEB3Qw0yFDG8wL/NPK5X/WBGRSaYymO5UGDFnbA2U=,tag:iFuNwWIpODhptb5kROEx0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
