---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: observability
  labels:
    app.kubernetes.io/name: unpoller
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9130
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: unpoller
