---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
patches:
  - target:
      kind: Namespace
      name: not-used
    patch: |
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: privileged
resources:
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  - ./loki/ks.yaml
  - ./unpoller/ks.yaml
  - ./homeassistant-metrics/ks.yaml
  - ./thanos/ks.yaml
