---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: games
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
