---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8sgpt
  namespace: k8sgpt-operator-system
spec:
  interval: 1h
  url: https://charts.k8sgpt.ai/
