---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-smb
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - forceuid
    - forcegid
    - noperm
    - mfsymlinks
    - nobrl            # Disable byte-range locking
    - cache=loose      # Better performance than strict
    - actimeo=60       # Cache file attributes for 60 seconds
    - noatime          # Don't update access timestamps
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: media-smb
    volumeAttributes:
      source: //192.168.100.180/Media
    nodeStageSecretRef:
      name: smb-creds
      namespace: kube-system
