apiVersion: v1
kind: Secret
metadata:
  name: meshmonitor-secrets
  namespace: radio
type: Opaque
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:YWZXVTgvZ9GCT+l0muz9zsiyUgv1N10cMBly1Howl6BCYsjWNzDBBD/XBbB1jpyFy3uQYJlORZUWQenn+3zbFw==,iv:4XIHDmgrScmYYklw5X24r5wOnmq8vY3wj58mVaP9SW0=,tag:9byJav/N3NsE2E0oob/nNA==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeWp2NTFZc1dZcnBMSVpT
        ZGtnWVk5bjVvdkhpSyszd3UzTjUvS21oNmswCkpVc0dZTWZpUkdWbmRFa1RaRy9L
        cEhQQ3BtMHhQR0lJWXN0RlRIeGpxdzgKLS0tIFNoaWlsaEJRRGxVcUE4MDBJRjFO
        UjJLaytmSVlicDQ5aGNxYkRWaVd0REUKhMmxfrqT7Upwl1EJK6HZNjasTxHj6B4S
        l2xiP4JUketZRASdYL8lzcsCHQLB6f9YubXwPEYYYpPqwWDeJ4gxRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T17:50:49Z"
  mac: ENC[AES256_GCM,data:/2P4bVQHtihXHKKe97GSdFRs89N2Byhd2FTxK4pb/vnoFOdN5TJhDEFDMcLdN7dDcpckwRbKieoCG6tFGPABnfzzaJnOLpzcWYSewsuu6U6h1bwfjwIcMio5wvGclHYekHBJ/gGa7kREt8OGxMn++T8AXZnPk1TJuJXHrWHbEnc=,iv:907ULWRv1dLYsBiNx3T/nywbFZerKOcA+fFQsBRFPr0=,tag:Kxslo786PpzlSs7ZyMAWGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
