apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KHkqiOK77Gws+3G/x3TiNpwrCw==,iv:NLJw6qFB4pbAcHC5nRZbL915n2I+0m51ahZFiaTrnAY=,tag:FxNdo4RYQwT5+kPlUefv2A==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M3JqblNpcDNHOXlSV3Y0
        c1d1OGRpZ1ZxUy9HaUthNGo2UEZMajd5djFVCjNScWxMK1FLRTR1WmdzTVorNFk2
        c1JNVXlmdC9LTTVYZ2lMaklWWFRxL1UKLS0tIGovQUJTSEtNSEFQYy85SkRESDEy
        MWtXSDk5QVpJOXcxME9DUnRSOXVudnMKuB1oQBaDbGpwjVFjbrQPez+EKBRdOX/F
        KajnhQgaajJ7IUkziK1IfrjZdGHJfZA2l3oYTpVchxhi5aG626xCgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T02:55:45Z"
  mac: ENC[AES256_GCM,data:MfhLoszAOWz+osVJgsz4qHV4fYxr7DL2mBkaYDUOJSs/tVEuGKn/SCKzWdtpIFU4GKO1JuJ4Zky2pt/oLp/ZFN9Kk5Xwjhn0RnuTWhpJfark8fPuEUJTVeONkKF2FUcPzxuZ5pEuL1CC79CdjvsDaMpEkP8P4PXKs1zsLxFe90k=,iv:KRyTYuVhofPiOhlS+lmNnxRBw/jDmmUobF/Z6NLZYZ0=,tag:4PU+TLA15IaA/pnzu86NSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
