apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nzvz23B/lg7CJDQDJ464xU1EwQ==,iv:WdlBeZlraGT0bJmOtukS6Ol2CgX+tTZHon8d7QB4WUs=,tag:bp8n/MYd7uadzPBVDCDAyw==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMnZoeXEyK29RVmRXM21j
        UjdhU0pjMEdpbjBUR0R3WktOcUUxR25valdNClNqcTFocG9idHlvR05BRUdnR1E5
        TkU4MFFMN2VLdktqVHpvK2dSckpHV3cKLS0tIDlIOEE2RjBUUFZJZmVsTHB2cDZ6
        ZkxDaTdYZncvY2htM3A5L3p5OG5yOVEKmspW6nTFu/5hhGw15xm9fPB85P7ynMLd
        I/zhiKkJnTPIKFfTJsBbfn5vHQyHLMDduwlft9OPi32i+SH2VcVNUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T02:21:53Z"
  mac: ENC[AES256_GCM,data:UqIzNXNF3Yq6wxrf5m7/MspHyk7b36rJdc1lk3vmWAMFBw46icP/MPQroGiKK9HYWKVgMAsefHrGTo1a3v659K0u6wa+Whf5xgA+lB8gtx5SSW61x06U8XsY5NF/tS3tNl/gfRPPgKRQUaOnpbBRso7tWcySPnAJ9OhMIlYBzwI=,iv:IQv1x6NCvDSgY0MFzRi4CRXiyLbc95GU1kZfA/9y1TI=,tag:iHwJvYJLw1B9C0VVy1KxlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
