apiVersion: v1
kind: Secret
metadata:
  name: open-webui-secrets
  namespace: ai
type: Opaque
stringData:
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:RXOIQL8v+bNxGCldq1kIbiorXpu1uClgrZfm6LYJ9yDdkp9ZkYN+l2VXb70=,iv:ZBTRQ59JDsPLZat0oXhSOj1fHe9s2yjcCvOGTlyCCBg=,tag:mBNHWiWla0bfZ4gZU4u97Q==,type:str]
sops:
  age:
    - recipient: age1pg85tdugypykuyaqtjzgmql4s9x9050emrgflhx0avx8ecut0pjssc24tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdzBaMUgxMnM2djkwd3ll
        azRRQ3lBdXNLS0crV3d0YVZFQW4vUXk3T0JRCnQzSkh1MGVNQ2lWSk5CN3VqdTBz
        MTZRdGxSMWFZbjJzYmZ0YlVtb2I4L1EKLS0tIEwrVDFScVVhMkhETktBWU4ycHBK
        L0wyVnhZM1dRaUM1TjZIMXNXcEwrSm8KYTvZWb9bqY3O1paYMMY9PXLXCaqw4gtl
        bskASbvzyyhx/Wi1g0Vqffl6R06Lh3cXRVXWxNgLeh+dgH1s3jSCig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T20:46:08Z"
  mac: ENC[AES256_GCM,data:wx+xVNAAynKOIYMc0gvSkmT+nCjXPpEz5DAqNmSVBOpxW1AKa0eDCBPFt/eNwDawfy+79fMsFuE5V7UHmqt8+JGmk49KeRRn6f+EoSSh/thnd8hNfnnGpcRLPRoROr5dETOQXkY9uZsiWINWtcsJJcYkcSc4RSfl8mF2oP2injg=,iv:TwG+pdk7r0aj+wbBqZTlL9vfDhSaGJaBh17YfFOi9+w=,tag:9Zclk3/gmfp1Z/IdB2OXoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
